#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/AppLog/_List_Data.cshtml")]
    public partial class _Areas_Admin_Views_AppLog__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<NewLife.Cube.Entity.AppLog>>
    {
        public _Areas_Admin_Views_AppLog__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var set = ViewBag.PageSetting as PageSetting;
    var provider = ManageProvider.Provider;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 20 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
             if (set.EnableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 23 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 807), Tuple.Create("\"", 846)
            
            #line 24 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 814), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 814), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 899), Tuple.Create("\"", 941)
            
            #line 25 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 906), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("AppID"))
            
            #line default
            #line hidden
, 906), false)
);

WriteLiteral(">应用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 994), Tuple.Create("\"", 1037)
            
            #line 26 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1001), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Action"))
            
            #line default
            #line hidden
, 1001), false)
);

WriteLiteral(">操作</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1090), Tuple.Create("\"", 1135)
            
            #line 27 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1097), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl(" Success"))
            
            #line default
            #line hidden
, 1097), false)
);

WriteLiteral(">成功</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">内容</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1233), Tuple.Create("\"", 1282)
            
            #line 29 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1240), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("CreateUserID"))
            
            #line default
            #line hidden
, 1240), false)
);

WriteLiteral(">创建者</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1336), Tuple.Create("\"", 1381)
            
            #line 30 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1343), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("CreateIP"))
            
            #line default
            #line hidden
, 1343), false)
);

WriteLiteral(">IP地址</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1461), Tuple.Create("\"", 1508)
            
            #line 31 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1468), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("CreateTime"))
            
            #line default
            #line hidden
, 1468), false)
);

WriteLiteral(">时间</a></th>\r\n");

            
            #line 32 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:100px;\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 35 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 39 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
         foreach (var entity in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 42 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 42 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                 if (set.EnableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1975), Tuple.Create("\"", 1993)
            
            #line 44 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 1983), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 1983), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 45 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 46 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                                   Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2102), Tuple.Create("\"", 2129)
, Tuple.Create(Tuple.Create("", 2109), Tuple.Create("App?ID=", 2109), true)
            
            #line 47 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2116), Tuple.Create<System.Object, System.Int32>(entity.AppID
            
            #line default
            #line hidden
, 2116), false)
);

WriteLiteral(">");

            
            #line 47 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                                              Write(entity.AppName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td>");

            
            #line 48 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
               Write(entity.Action);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 2262), Tuple.Create("\"", 2325)
, Tuple.Create(Tuple.Create("", 2270), Tuple.Create("glyphicon", 2270), true)
, Tuple.Create(Tuple.Create(" ", 2279), Tuple.Create("glyphicon-", 2280), true)
            
            #line 50 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2290), Tuple.Create<System.Object, System.Int32>(entity.Success ? "ok" : "remove"
            
            #line default
            #line hidden
, 2290), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 2326), Tuple.Create("\"", 2377)
, Tuple.Create(Tuple.Create("", 2334), Tuple.Create("color:", 2334), true)
            
            #line 50 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                     , Tuple.Create(Tuple.Create(" ", 2340), Tuple.Create<System.Object, System.Int32>(entity.Success ? "green" : "red"
            
            #line default
            #line hidden
, 2341), false)
, Tuple.Create(Tuple.Create("", 2376), Tuple.Create(";", 2376), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" style=\"max-width:600px;overflow:hidden;white-space: nowrap;text-overflow: ellips" +
"is;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2512), Tuple.Create("\"", 2534)
            
            #line 52 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                                , Tuple.Create(Tuple.Create("", 2520), Tuple.Create<System.Object, System.Int32>(entity.Remark
            
            #line default
            #line hidden
, 2520), false)
);

WriteLiteral(">");

            
            #line 52 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                                                                                                                           Write(entity.Remark);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 53 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                                  Write(UserX.FindByID(entity.CreateUserID));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 2658), Tuple.Create("\"", 2696)
            
            #line 54 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2666), Tuple.Create<System.Object, System.Int32>(entity.CreateIP.IPToAddress()
            
            #line default
            #line hidden
, 2666), false)
);

WriteLiteral(">");

            
            #line 54 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                                                      Write(entity.CreateIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 55 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
               Write(entity.CreateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 56 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 56 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 59 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 61 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 63 "..\..\Areas\Admin\Views\AppLog\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
