#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Index/Index.cshtml")]
    public partial class _Areas_Admin_Views_Index_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Index_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Admin\Views\Index\Index.cshtml"
  
    Layout = null;

    var User = ViewBag.User;
    var cfg = NewLife.Common.SysConfig.Current;

    var title = ViewBag.Title + "";
    if (title != "" && !title.EndsWith(" - ")) { title += " - "; }
    title += cfg.DisplayName;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"zh-CN\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(" />\r\n    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->\r\n\r\n    <title>");

            
            #line 19 "..\..\Areas\Admin\Views\Index\Index.cshtml"
      Write(title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 546), Tuple.Create("\"", 566)
, Tuple.Create(Tuple.Create("", 553), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 553), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n\r\n    <!-- bootstrap & fontawesome -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 661), Tuple.Create("\"", 701)
, Tuple.Create(Tuple.Create("", 668), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/bootstrap.min.css")
, 668), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 733), Tuple.Create("\"", 789)
, Tuple.Create(Tuple.Create("", 740), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/font-awesome/css/font-awesome.min.css")
, 740), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 821), Tuple.Create("\"", 855)
, Tuple.Create(Tuple.Create("", 828), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/animate.css")
, 828), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 887), Tuple.Create("\"", 919)
, Tuple.Create(Tuple.Create("", 894), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/style.css")
, 894), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <!-- 自定义样式 -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 988), Tuple.Create("\"", 1015)
, Tuple.Create(Tuple.Create("", 995), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/Cube.css")
, 995), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    \r\n\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" id=\"wrapper\"");

WriteLiteral(">\r\n        <!-- navbar -->\r\n        <nav");

WriteLiteral(" class=\"navbar-default navbar-static-side\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 36 "..\..\Areas\Admin\Views\Index\Index.cshtml"
       Write(Html.Partial("_Left"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </nav>\r\n\r\n        <!-- page-wrapper -->\r\n        <div");

WriteLiteral(" id=\"page-wrapper\"");

WriteLiteral(" class=\"gray-bg\"");

WriteLiteral(">\r\n            <!-- navbar-header -->\r\n            <div");

WriteLiteral(" class=\"row border-bottom\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 43 "..\..\Areas\Admin\Views\Index\Index.cshtml"
           Write(Html.Partial("_Navbar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n\r\n            <!-- -->\r\n            <div");

WriteLiteral(" class=\"wrapper wrapper-content\"");

WriteLiteral(">\r\n                <iframe");

WriteLiteral(" style=\"width: 100%; height: 100%; margin: 0; padding: 0; border: none;\"");

WriteLiteral(" id=\"main\"");

WriteLiteral(" name=\"main\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1655), Tuple.Create("\"", 1674)
            
            #line 48 "..\..\Areas\Admin\Views\Index\Index.cshtml"
                                           , Tuple.Create(Tuple.Create("", 1661), Tuple.Create<System.Object, System.Int32>(ViewBag.Main
            
            #line default
            #line hidden
, 1661), false)
);

WriteLiteral("></iframe>\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n\r\n    <!-- Mainly s" +
"cripts -->\r\n    <!-- JQuery作为一等公民，页面内部随时可能使用 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1817), Tuple.Create("\"", 1857)
, Tuple.Create(Tuple.Create("", 1823), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/jquery-3.1.1.min.js")
, 1823), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1881), Tuple.Create("\"", 1918)
, Tuple.Create(Tuple.Create("", 1887), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/bootstrap.min.js")
, 1887), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1942), Tuple.Create("\"", 2000)
, Tuple.Create(Tuple.Create("", 1948), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/plugins/metisMenu/jquery.metisMenu.js")
, 1948), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2024), Tuple.Create("\"", 2088)
, Tuple.Create(Tuple.Create("", 2030), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/plugins/slimscroll/jquery.slimscroll.min.js")
, 2030), false)
);

WriteLiteral("></script>\r\n\r\n    <!-- Custom and plugin javascript -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2157), Tuple.Create("\"", 2189)
, Tuple.Create(Tuple.Create("", 2163), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/inspinia.js")
, 2163), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2213), Tuple.Create("\"", 2258)
, Tuple.Create(Tuple.Create("", 2219), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/plugins/pace/pace.min.js")
, 2219), false)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(function () {
            var $frmContent = $('#main');
            function fixFrmContentSize() {
                var offset = $frmContent.offset();
                var top = offset.top;
                var height = document.documentElement.clientHeight;
                $frmContent.height(height - top - 10);
            }
            fixFrmContentSize();
            $(window).resize(fixFrmContentSize);

            //增加iframe被嵌套的检测2015-6-4 景裔增加
            if (window != top) {
                top.location.href = location.href;
            }
        });

    </script>
</body>
</html>");

        }
    }
}
#pragma warning restore 1591
