#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
    using NewLife.Cube.Entity;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    
    #line 4 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/UserToken/_List_Data.cshtml")]
    public partial class _Areas_Admin_Views_UserToken__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<UserToken>>
    {
        public _Areas_Admin_Views_UserToken__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 9 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var set = ViewBag.PageSetting as PageSetting;
    var provider = ManageProvider.Provider;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
             if (set.EnableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 756), Tuple.Create("\"", 795)
            
            #line 23 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 763), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 763), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 848), Tuple.Create("\"", 890)
            
            #line 24 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 855), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Token"))
            
            #line default
            #line hidden
, 855), false)
);

WriteLiteral(">令牌</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"地址。锁定该令牌只能访问该资源路径\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 969), Tuple.Create("\"", 1009)
            
            #line 25 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 976), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Url"))
            
            #line default
            #line hidden
, 976), false)
);

WriteLiteral(">地址</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">页面</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">Json数据</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">Xml数据</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"用户。本地用户\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1220), Tuple.Create("\"", 1263)
            
            #line 29 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1227), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UserID"))
            
            #line default
            #line hidden
, 1227), false)
);

WriteLiteral(">用户</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1341), Tuple.Create("\"", 1384)
            
            #line 30 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1348), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Expire"))
            
            #line default
            #line hidden
, 1348), false)
);

WriteLiteral(">过期时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1439), Tuple.Create("\"", 1482)
            
            #line 31 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1446), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Enable"))
            
            #line default
            #line hidden
, 1446), false)
);

WriteLiteral(">启用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"次数。该令牌使用次数\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1554), Tuple.Create("\"", 1596)
            
            #line 32 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1561), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Times"))
            
            #line default
            #line hidden
, 1561), false)
);

WriteLiteral(">次数</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1649), Tuple.Create("\"", 1692)
            
            #line 33 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1656), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("LastIP"))
            
            #line default
            #line hidden
, 1656), false)
);

WriteLiteral(">最后地址</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1772), Tuple.Create("\"", 1817)
            
            #line 34 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1779), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("LastTime"))
            
            #line default
            #line hidden
, 1779), false)
);

WriteLiteral(">最后时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1872), Tuple.Create("\"", 1917)
            
            #line 35 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1879), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateIP"))
            
            #line default
            #line hidden
, 1879), false)
);

WriteLiteral(">更新地址</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1997), Tuple.Create("\"", 2044)
            
            #line 36 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2004), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateTime"))
            
            #line default
            #line hidden
, 2004), false)
);

WriteLiteral(">更新时间</a></th>\r\n");

            
            #line 37 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 40 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 44 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
         foreach (var entity in Model)
        {
            var url = entity.Url + "";
            var query = "";
            var p = url.IndexOf('?');
            if (p >= 0)
            {
                query = url.Substring(p);
                url = url.Substring(0, p);
            }
            if (!query.IsNullOrEmpty())
            {
                query += "&token=" + entity.Token;
            }
            else
            {
                query += "?token=" + entity.Token;
            }


            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 64 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 64 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                 if (set.EnableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2963), Tuple.Create("\"", 2981)
            
            #line 66 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 2971), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2971), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 67 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 68 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                                   Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 69 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
               Write(entity.Token);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" style=\"max-width:400px;overflow:hidden;white-space: nowrap;text-overflow: ellips" +
"is;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 3212), Tuple.Create("\"", 3231)
            
            #line 70 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                                , Tuple.Create(Tuple.Create("", 3220), Tuple.Create<System.Object, System.Int32>(entity.Url
            
            #line default
            #line hidden
, 3220), false)
);

WriteLiteral(">");

            
            #line 70 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                                                                                                                        Write(entity.Url);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3293), Tuple.Create("\"", 3320)
            
            #line 71 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3300), Tuple.Create<System.Object, System.Int32>(url+"/Html"+query
            
            #line default
            #line hidden
, 3300), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">页面</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3393), Tuple.Create("\"", 3420)
            
            #line 72 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3400), Tuple.Create<System.Object, System.Int32>(url+"/Json"+query
            
            #line default
            #line hidden
, 3400), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">Json数据</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3497), Tuple.Create("\"", 3523)
            
            #line 73 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3504), Tuple.Create<System.Object, System.Int32>(url+"/Xml"+query
            
            #line default
            #line hidden
, 3504), false)
);

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">Xml数据</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 74 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                                   Write(entity.UserName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 75 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                                   Write(entity.Expire.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3762), Tuple.Create("\"", 3824)
, Tuple.Create(Tuple.Create("", 3770), Tuple.Create("glyphicon", 3770), true)
, Tuple.Create(Tuple.Create(" ", 3779), Tuple.Create("glyphicon-", 3780), true)
            
            #line 77 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3790), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "ok" : "remove"
            
            #line default
            #line hidden
, 3790), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 3825), Tuple.Create("\"", 3875)
, Tuple.Create(Tuple.Create("", 3833), Tuple.Create("color:", 3833), true)
            
            #line 77 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                    , Tuple.Create(Tuple.Create(" ", 3839), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "green" : "red"
            
            #line default
            #line hidden
, 3840), false)
, Tuple.Create(Tuple.Create("", 3874), Tuple.Create(";", 3874), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 79 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                                  Write(entity.Times.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 80 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
               Write(entity.LastIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 81 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                                   Write(entity.LastTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 82 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                                   Write(provider.FindByID(entity.UpdateUserID));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteAttribute("title", Tuple.Create(" title=\"", 4226), Tuple.Create("\"", 4264)
            
            #line 83 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 4234), Tuple.Create<System.Object, System.Int32>(entity.UpdateIP.IPToAddress()
            
            #line default
            #line hidden
, 4234), false)
);

WriteLiteral(">");

            
            #line 83 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                                                                          Write(entity.UpdateIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 84 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
               Write(entity.Remark);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 85 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 85 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 88 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 90 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 92 "..\..\Areas\Admin\Views\UserToken\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
