#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    
    #line 2 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
    using NewLife.Cube.Charts;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Bootstrap_Layout.cshtml")]
    public partial class _Views_Shared__Bootstrap_Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Bootstrap_Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
  
    var set = NewLife.Cube.Setting.Current;
    var set2 = ViewBag.PageSetting as PageSetting;

    var charts = ViewBag.Charts as ECharts[];
    var charts2 = ViewBag.Charts2 as ECharts[];

    var title = ViewBag.Title + "";
    if (title != "" && !title.Contains(" - "))
    {
        title += " - " + NewLife.Common.SysConfig.Current.DisplayName;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"zh-CN\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 22 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
      Write(title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 677), Tuple.Create("\"", 697)
, Tuple.Create(Tuple.Create("", 684), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 684), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n\r\n    <!-- 页面内联样式 -->\r\n");

WriteLiteral("    ");

            
            #line 26 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
Write(RenderSection("css", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 28 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
     if (set != null && set.BootstrapSelect)
    {

            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 893), Tuple.Create("\"", 949)
, Tuple.Create(Tuple.Create("", 900), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/css/bootstrap-multiselect.css")
, 900), false)
);

WriteLiteral(">\r\n");

            
            #line 31 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 988), Tuple.Create("\"", 1052)
, Tuple.Create(Tuple.Create("", 995), Tuple.Create<System.Object, System.Int32>(Href("~/Content/DateTimePicker/bootstrap-datetimepicker.min.css")
, 995), false)
);

WriteLiteral(">\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1084), Tuple.Create("\"", 1142)
, Tuple.Create(Tuple.Create("", 1091), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap-switch/bootstrap-switch.min.css")
, 1091), false)
);

WriteLiteral(">\r\n\r\n    <!-- 最后引入基本样式 -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1197), Tuple.Create("\"", 1247)
, Tuple.Create(Tuple.Create("", 1204), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/bootstrap.min-4.4.1.css")
, 1204), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1277), Tuple.Create("\"", 1328)
, Tuple.Create(Tuple.Create("", 1284), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/css/font-awesome.min.css")
, 1284), false)
);

WriteLiteral(">\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1360), Tuple.Create("\"", 1414)
, Tuple.Create(Tuple.Create("", 1367), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/css/bootstrap-theme.min.css")
, 1367), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1444), Tuple.Create("\"", 1503)
, Tuple.Create(Tuple.Create("", 1451), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/css/bootstrap-responsive.min.css")
, 1451), false)
);

WriteLiteral(">\r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1518), Tuple.Create("\"", 1562)
, Tuple.Create(Tuple.Create("", 1525), Tuple.Create<System.Object, System.Int32>(Href("~/Content/artDialog/css/ui-dialog.css")
, 1525), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <!-- 自定义样式 -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1633), Tuple.Create("\"", 1684)
, Tuple.Create(Tuple.Create("", 1640), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Cube-bootstrap.css?v=3.2.2020.0222")
, 1640), false)
);

WriteLiteral(">\r\n    <!-- JQuery作为一等公民，页面内部随时可能使用 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1737), Tuple.Create("\"", 1775)
, Tuple.Create(Tuple.Create("", 1743), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery-3.4.1.min.js")
, 1743), false)
);

WriteLiteral("></script>\r\n");

            
            #line 50 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
     if (charts != null && charts.Length > 0 || charts2 != null && charts2.Length > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1898), Tuple.Create("\"", 1928)
, Tuple.Create(Tuple.Create("", 1904), Tuple.Create<System.Object, System.Int32>(Href("~/Content/echarts.min.js")
, 1904), false)
);

WriteLiteral("></script>\r\n");

            
            #line 53 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n");

            
            #line 57 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
         if (set2 != null && set2.EnableNavbar)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"breadcrumbs\"");

WriteLiteral(" id=\"breadcrumbs\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 61 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
               Write(Html.Partial("_Layout_Nav"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </ul>\r\n                <div");

WriteLiteral(" style=\"float: right; margin-left: 40px;\"");

WriteLiteral(">");

            
            #line 63 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
                                                         Write(ViewBag.HeaderContent);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n");

            
            #line 65 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"page-content\"");

WriteLiteral(">\r\n            <section");

WriteLiteral(" class=\"content-wrapper main-content clear-fix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 68 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </section>\r\n        </div>\r\n");

            
            #line 71 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
         if (DbRunTimeModule.Enable)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 74 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
           Write(Html.Raw(DbRunTimeModule.GetInfo()));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 76 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    <!-- 最早引入基本脚本 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2754), Tuple.Create("\"", 2809)
, Tuple.Create(Tuple.Create("", 2760), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/bootstrap.bundle.min-4.4.1.js")
, 2760), false)
);

WriteLiteral("></script>\r\n");

            
            #line 80 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
     if (set != null && set.BootstrapSelect)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2890), Tuple.Create("\"", 2947)
, Tuple.Create(Tuple.Create("", 2896), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap/js/bootstrap-multiselect.min.js")
, 2896), false)
);

WriteLiteral("></script>\r\n");

            
            #line 83 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 85 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <!--日历控件支持-->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3049), Tuple.Create("\"", 3111)
, Tuple.Create(Tuple.Create("", 3055), Tuple.Create<System.Object, System.Int32>(Href("~/Content/DateTimePicker/bootstrap-datetimepicker.min.js")
, 3055), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3135), Tuple.Create("\"", 3207)
, Tuple.Create(Tuple.Create("", 3141), Tuple.Create<System.Object, System.Int32>(Href("~/Content/DateTimePicker/locales/bootstrap-datetimepicker.zh-CN.js")
, 3141), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            $(\'.form_datetime\'" +
").each(function () {\r\n                var df = $(this).attr(\'dateformat\');\r\n    " +
"            if (!df) {\r\n                    $(this).attr(\'dateformat\', \'yyyy-mm-" +
"dd hh:ii:ss\');\r\n                    $(this).width(140);\r\n                }\r\n    " +
"            else {\r\n                    // 把C#标准格式化替换为控件格式\r\n                    " +
"df = df.replace(\'mm\', \'ii\').replace(\'MM\', \'mm\').replace(\'HH\', \'hh\');\r\n          " +
"          $(this).attr(\'dateformat\', df);\r\n\r\n                    // 根据时间日期格式，锁定日" +
"期输入框宽度\r\n                    if (df.indexOf(\'hh\') >= 0)\r\n                        " +
"$(this).width(140);\r\n                    else\r\n                        $(this).w" +
"idth(80);\r\n                }\r\n\r\n                //根据日期格式自动推算日期选择view显示的范围\r\n     " +
"           var sv = 2;\r\n                var mv = 2;\r\n                var autoVie" +
"w = $(this).attr(\'autoView\');\r\n                if (autoView != \'false\') {\r\n     " +
"               df = $(this).attr(\'dateformat\');\r\n                    if (df.inde" +
"xOf(\'ii\') >= 0) {\r\n                        mv = 0;\r\n                        if (" +
"df.indexOf(\'dd\') >= 0) {\r\n                            sv = 2;\r\n                 " +
"       } else {\r\n                            sv = 1;\r\n                        }\r" +
"\n                    } else if (df.indexOf(\'hh\') >= 0) {\r\n                      " +
"  mv = 1;\r\n                        if (df.indexOf(\'dd\') >= 0) {\r\n               " +
"             sv = 2;\r\n                        } else {\r\n                        " +
"    sv = 1;\r\n                        }\r\n                    } else if (df.indexO" +
"f(\'dd\') >= 0) {\r\n                        mv = 2;\r\n                        sv = 2" +
";\r\n                    } else if (df.indexOf(\'mm\') >= 0) {\r\n                    " +
"    mv = 3;\r\n                        sv = 3;\r\n                    } else if (df." +
"indexOf(\'yyyy\') >= 0) {\r\n                        mv = 4;\r\n                      " +
"  sv = 4;\r\n                    }\r\n                }\r\n\r\n                $(this).a" +
"ttr(\'startview\', sv);\r\n                $(this).attr(\'minview\', mv);\r\n           " +
" });\r\n            $(\"[dateformat]\").each(function () {\r\n                $(this)." +
"datetimepicker({\r\n                    format: $(this).attr(\"dateformat\"),\r\n     " +
"               autoclose: true,\r\n                    language: \"zh-CN\",\r\n       " +
"             forceParse: false,\r\n                    startView: parseInt($(this)" +
".attr(\'startview\')),\r\n                    minView: parseInt($(this).attr(\'minvie" +
"w\'))\r\n                });\r\n            });\r\n");

            
            #line 155 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 155 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
             if (set != null && set.BootstrapSelect) {
            
            #line default
            #line hidden
WriteLiteral(@"
            $('.multiselect').each(function () {
                $(this).multiselect({
                    // 下拉列表仅在列表项比较多时显示过滤框
                    enableFiltering: $(this).children().length > 10,
                    buttonClass: 'btn btn-white btn-primary',
                    templates: {
                        button: '<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"multiselect dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral("></button>\',\r\n                        ul: \'<ul");

WriteLiteral(" class=\"multiselect-container dropdown-menu\"");

WriteLiteral("></ul>\',\r\n                        filter: \'<li");

WriteLiteral(" class=\"multiselect-item filter\"");

WriteLiteral("><div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral("><span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i></span><input");

WriteLiteral(" class=\"form-control multiselect-search\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("></div></li>\',\r\n                        filterClearBtn: \'<span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral("><button");

WriteLiteral(" class=\"btn btn-default btn-white btn-grey multiselect-clear-filter\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-times-circle red2\"");

WriteLiteral("></i></button></span>\',\r\n                        li: \'<li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral("><label></label></a></li>\',\r\n                        divider: \'<li");

WriteLiteral(" class=\"multiselect-item divider\"");

WriteLiteral("></li>\',\r\n                        liGroup: \'<li");

WriteLiteral(" class=\"multiselect-item group\"");

WriteLiteral("><label");

WriteLiteral(" class=\"multiselect-group\"");

WriteLiteral("></label></li>\'\r\n                    },\r\n                    filterPlaceholder: \'" +
"搜索\',\r\n                    nonSelectedText: \'无\',\r\n                    allSelected" +
"Text: \'全选\'\r\n                });\r\n            });\r\n            ");

            
            #line 175 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
                   }
            
            
            #line default
            #line hidden
            
            #line 178 "..\..\Views\Shared\_Bootstrap_Layout.cshtml"
                                                                                        

            
            #line default
            #line hidden
WriteLiteral(@"            $('tr').dblclick(function () {
                var $this = $(this);
                var row = $this.closest(""tr"");
                var findcell = row.find('.editcell');
                if (findcell.length > 0) window.location.href = findcell.attr(""href"");
            });
        });
    </script>

    <!--开关插件-->
    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 7770), Tuple.Create("\"", 7826)
, Tuple.Create(Tuple.Create("", 7776), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap-switch/bootstrap-switch.min.js")
, 7776), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            $(\"input.chkSwitch" +
"\").bootstrapSwitch();\r\n        })\r\n    </script>\r\n\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 7990), Tuple.Create("\"", 8039)
, Tuple.Create(Tuple.Create("", 7996), Tuple.Create<System.Object, System.Int32>(Href("~/Content/artDialog/dist/dialog-plus-min.js")
, 7996), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 8063), Tuple.Create("\"", 8112)
, Tuple.Create(Tuple.Create("", 8069), Tuple.Create<System.Object, System.Int32>(Href("~/Content/artDialog/dist/dialog.new.life.js")
, 8069), false)
);

WriteLiteral("></script>\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 8157), Tuple.Create("\"", 8196)
, Tuple.Create(Tuple.Create("", 8163), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Cube.js?v=3.2.2020.0204")
, 8163), false)
);

WriteLiteral("></script>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
