#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\_ECharts.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_ECharts.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    
    #line 3 "..\..\Views\Shared\_ECharts.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\_ECharts.cshtml"
    using XCode;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_ECharts.cshtml")]
    public partial class _Views_Shared__ECharts_cshtml : System.Web.Mvc.WebViewPage<NewLife.Cube.Charts.ECharts>
    {
        public _Views_Shared__ECharts_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Shared\_ECharts.cshtml"
  
    var chart = Model;
    var name = chart.Name;
    var chartName = "chart_" + name;
    var optionName = "option_" + name;

    var style = chart.Style;
    if (chart.Width > 0)
    {
        style += "width: {0}px;".F(chart.Width);
    }
    else if (chart.Width < 0)
    {
        style += "width: {0}%;".F(-chart.Width);
    }

    if (chart.Height > 0)
    {
        style += "height: {0}px;".F(chart.Height);
    }
    else if (chart.Height < 0)
    {
        style += "height: {0}%;".F(-chart.Height);
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteAttribute("id", Tuple.Create(" id=\"", 662), Tuple.Create("\"", 672)
            
            #line 31 "..\..\Views\Shared\_ECharts.cshtml"
, Tuple.Create(Tuple.Create("", 667), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 667), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 673), Tuple.Create("\"", 687)
            
            #line 31 "..\..\Views\Shared\_ECharts.cshtml"
, Tuple.Create(Tuple.Create("", 681), Tuple.Create<System.Object, System.Int32>(style
            
            #line default
            #line hidden
, 681), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 688), Tuple.Create("\"", 708)
            
            #line 31 "..\..\Views\Shared\_ECharts.cshtml"
, Tuple.Create(Tuple.Create("", 696), Tuple.Create<System.Object, System.Int32>(chart.Class
            
            #line default
            #line hidden
, 696), false)
);

WriteLiteral("></div>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var ");

            
            #line 33 "..\..\Views\Shared\_ECharts.cshtml"
   Write(chartName);

            
            #line default
            #line hidden
WriteLiteral(" = echarts.init(document.getElementById(\'");

            
            #line 33 "..\..\Views\Shared\_ECharts.cshtml"
                                                      Write(name);

            
            #line default
            #line hidden
WriteLiteral("\'));\r\n    var ");

            
            #line 34 "..\..\Views\Shared\_ECharts.cshtml"
   Write(optionName);

            
            #line default
            #line hidden
WriteLiteral(" = ");

            
            #line 34 "..\..\Views\Shared\_ECharts.cshtml"
                 Write(Html.Raw(chart.Build()));

            
            #line default
            #line hidden
WriteLiteral(";\r\n");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Shared\_ECharts.cshtml"
Write(chartName);

            
            #line default
            #line hidden
WriteLiteral(".setOption(");

            
            #line 35 "..\..\Views\Shared\_ECharts.cshtml"
                      Write(optionName);

            
            #line default
            #line hidden
WriteLiteral(");\r\n</script>");

        }
    }
}
#pragma warning restore 1591
