#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Footer.cshtml")]
    public partial class _Views_Shared__Footer_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Footer_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_Footer.cshtml"
  
    var set = NewLife.Cube.Setting.Current;

            
            #line default
            #line hidden
WriteLiteral("\r\n<footer>\r\n    <div");

WriteLiteral(" style=\"margin-top:20px;\"");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Views\Shared\_Footer.cshtml"
        
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\_Footer.cshtml"
         if (!set.Copyright.IsNullOrEmpty())
        {

            
            #line default
            #line hidden
WriteLiteral("            <span>");

            
            #line 8 "..\..\Views\Shared\_Footer.cshtml"
             Write(set.Copyright);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 9 "..\..\Views\Shared\_Footer.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 10 "..\..\Views\Shared\_Footer.cshtml"
         if (!set.Registration.IsNullOrEmpty())
        {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" href=\"http://www.beian.miit.gov.cn\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">");

            
            #line 12 "..\..\Views\Shared\_Footer.cshtml"
                                                              Write(set.Registration);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 13 "..\..\Views\Shared\_Footer.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</footer>");

        }
    }
}
#pragma warning restore 1591
