#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Views\Shared\_Form_Footer.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    
    #line 2 "..\..\Views\Shared\_Form_Footer.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Form_Footer.cshtml")]
    public partial class _Views_Shared__Form_Footer_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Form_Footer_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_Form_Footer.cshtml"
  
    //var entity = Model as IEntity;
    //var fact = EntityFactory.CreateOperate(entity.GetType());
    //var fields = ViewBag.Fields as IList<FieldItem>;

    //var set = NewLife.Cube.Setting.Current;
    //var cls = set.FormGroupClass;
    //if (cls.IsNullOrEmpty()) { cls = "form-group col-xs-12 col-sm-6 col-lg-4"; }

    //var total = 12;
    //var label = 4;
    //var span = 0;
    //var input = total - label - span;

    //var cid = fact.Table.FindByName("CreateUserID") as FieldItem;
    //var uid = fact.Table.FindByName("UpdateUserID") as FieldItem;
    //var cip = fact.Table.FindByName("CreateIP") as FieldItem;
    //var uip = fact.Table.FindByName("UpdateIP") as FieldItem;
    //var remark = fact.Table.FindByName("Remark") as FieldItem;
    //if (remark == null) { remark = fact.Table.FindByName("Description"); }

    //var hasUser = cid != null || uid != null;
    //if (hasUser && ViewData["Provider"] == null) { ViewData["Provider"] = ManageProvider.Provider; }
    //var provider = ViewData["Provider"] as IManageProvider;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
