#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 1 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Inspinia_Layout.cshtml")]
    public partial class _Views_Shared__Inspinia_Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Inspinia_Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
  
    var set = NewLife.Cube.Setting.Current;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"zh-CN\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"新生命团队,NewLife,魔方,Cube,XCode\"");

WriteLiteral(" />\r\n    ");

WriteLiteral("\r\n    <title>");

            
            #line 13 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 13 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
                       Write(SysConfig.Current.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 477), Tuple.Create("\"", 497)
, Tuple.Create(Tuple.Create("", 484), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 484), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 552), Tuple.Create("\"", 592)
, Tuple.Create(Tuple.Create("", 559), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/bootstrap.min.css")
, 559), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 624), Tuple.Create("\"", 680)
, Tuple.Create(Tuple.Create("", 631), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/font-awesome/css/font-awesome.min.css")
, 631), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 712), Tuple.Create("\"", 746)
, Tuple.Create(Tuple.Create("", 719), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/animate.css")
, 719), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 778), Tuple.Create("\"", 810)
, Tuple.Create(Tuple.Create("", 785), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/style.css")
, 785), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <!-- plugins css -->\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 870), Tuple.Create("\"", 948)
, Tuple.Create(Tuple.Create("", 877), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/plugins/datetimepicker/bootstrap-datetimepicker.min.css")
, 877), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 980), Tuple.Create("\"", 1042)
, Tuple.Create(Tuple.Create("", 987), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/plugins/switch/bootstrap-switch.min.css")
, 987), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1074), Tuple.Create("\"", 1162)
, Tuple.Create(Tuple.Create("", 1081), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" +
"")
, 1081), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1194), Tuple.Create("\"", 1250)
, Tuple.Create(Tuple.Create("", 1201), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/plugins/sweetalert/sweetalert.css")
, 1201), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <!-- 页面内联样式 -->\r\n");

WriteLiteral("    ");

            
            #line 28 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
Write(RenderSection("css", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 30 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
     if (set.BootstrapSelect)
    {

            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1410), Tuple.Create("\"", 1464)
, Tuple.Create(Tuple.Create("", 1417), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/plugins/select2/select2.min.css")
, 1417), false)
);

WriteLiteral(">\r\n");

            
            #line 33 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1505), Tuple.Create("\"", 1567)
, Tuple.Create(Tuple.Create("", 1512), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/css/plugins/switch/bootstrap-switch.min.css")
, 1512), false)
);

WriteLiteral(">\r\n\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n    <!-- 自定义样式 -->\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1726), Tuple.Create("\"", 1753)
, Tuple.Create(Tuple.Create("", 1733), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/Cube.css")
, 1733), false)
);

WriteLiteral(">\r\n    <!-- JQuery作为一等公民，页面内部随时可能使用 -->\r\n\r\n    <!-- Mainly scripts -->\r\n    <scri" +
"pt");

WriteAttribute("src", Tuple.Create(" src=\"", 1837), Tuple.Create("\"", 1877)
, Tuple.Create(Tuple.Create("", 1843), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/jquery-3.1.1.min.js")
, 1843), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1901), Tuple.Create("\"", 1938)
, Tuple.Create(Tuple.Create("", 1907), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/bootstrap.min.js")
, 1907), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1962), Tuple.Create("\"", 2020)
, Tuple.Create(Tuple.Create("", 1968), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/plugins/metisMenu/jquery.metisMenu.js")
, 1968), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2044), Tuple.Create("\"", 2108)
, Tuple.Create(Tuple.Create("", 2050), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/plugins/slimscroll/jquery.slimscroll.min.js")
, 2050), false)
);

WriteLiteral("></script>\r\n\r\n    <!-- Custom and plugin javascript -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2177), Tuple.Create("\"", 2209)
, Tuple.Create(Tuple.Create("", 2183), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/inspinia.js")
, 2183), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2233), Tuple.Create("\"", 2278)
, Tuple.Create(Tuple.Create("", 2239), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/plugins/pace/pace.min.js")
, 2239), false)
);

WriteLiteral("></script>\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"breadcrumbs\"");

WriteLiteral(" id=\"breadcrumbs\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 59 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
           Write(Html.Partial("_Inspinia_Layout_Nav"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </ul>\r\n            <div");

WriteLiteral(" style=\"float: right; margin-left: 40px;\"");

WriteLiteral(">");

            
            #line 61 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
                                                     Write(ViewBag.HeaderContent);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"page-content\"");

WriteLiteral(">\r\n            <section");

WriteLiteral(" class=\"content-wrapper main-content clear-fix\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 65 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </section>\r\n        </div>\r\n");

            
            #line 68 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
         if (DbRunTimeModule.Enable)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 71 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
           Write(Html.Raw(DbRunTimeModule.GetInfo()));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 73 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    <!-- 最早引入基本脚本 -->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3011), Tuple.Create("\"", 3048)
, Tuple.Create(Tuple.Create("", 3017), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/bootstrap.min.js")
, 3017), false)
);

WriteLiteral("></script>\r\n");

            
            #line 77 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
     if (set.BootstrapSelect)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3114), Tuple.Create("\"", 3170)
, Tuple.Create(Tuple.Create("", 3120), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/plugins/select2/select2.full.min.js")
, 3120), false)
);

WriteLiteral("></script>\r\n");

            
            #line 80 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 82 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <!--日历控件支持-->\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3272), Tuple.Create("\"", 3347)
, Tuple.Create(Tuple.Create("", 3278), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/plugins/datetimepicker/bootstrap-datetimepicker.min.js")
, 3278), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3371), Tuple.Create("\"", 3456)
, Tuple.Create(Tuple.Create("", 3377), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/plugins/datetimepicker/locales/bootstrap-datetimepicker.zh-CN.js")
, 3377), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            $(\'.form_datetime\'" +
").each(function () {\r\n                var df = $(this).attr(\'dateformat\');\r\n    " +
"            if (!df) {\r\n                    $(this).attr(\'dateformat\', \'yyyy-mm-" +
"dd hh:ii:ss\');\r\n                    $(this).width(140);\r\n                }\r\n    " +
"            else {\r\n                    // 把C#标准格式化替换为控件格式\r\n                    " +
"df = df.replace(\'mm\', \'ii\').replace(\'MM\', \'mm\').replace(\'HH\', \'hh\');\r\n          " +
"          $(this).attr(\'dateformat\', df);\r\n\r\n                    // 根据时间日期格式，锁定日" +
"期输入框宽度\r\n                    if (df.indexOf(\'hh\') >= 0)\r\n                        " +
"$(this).width(140);\r\n                    else\r\n                        $(this).w" +
"idth(80);\r\n                }\r\n\r\n                //根据日期格式自动推算日期选择view显示的范围\r\n     " +
"           var sv = 2;\r\n                var mv = 2;\r\n                var autoVie" +
"w = $(this).attr(\'autoView\');\r\n                if (autoView != \'false\') {\r\n     " +
"               df = $(this).attr(\'dateformat\');\r\n                    if (df.inde" +
"xOf(\'ii\') >= 0) {\r\n                        mv = 0;\r\n                        if (" +
"df.indexOf(\'dd\') >= 0) {\r\n                            sv = 2;\r\n                 " +
"       } else {\r\n                            sv = 1;\r\n                        }\r" +
"\n                    } else if (df.indexOf(\'hh\') >= 0) {\r\n                      " +
"  mv = 1;\r\n                        if (df.indexOf(\'dd\') >= 0) {\r\n               " +
"             sv = 2;\r\n                        } else {\r\n                        " +
"    sv = 1;\r\n                        }\r\n                    } else if (df.indexO" +
"f(\'dd\') >= 0) {\r\n                        mv = 2;\r\n                        sv = 2" +
";\r\n                    } else if (df.indexOf(\'mm\') >= 0) {\r\n                    " +
"    mv = 3;\r\n                        sv = 3;\r\n                    } else if (df." +
"indexOf(\'yyyy\') >= 0) {\r\n                        mv = 4;\r\n                      " +
"  sv = 4;\r\n                    }\r\n                }\r\n\r\n                $(this).a" +
"ttr(\'startview\', sv);\r\n                $(this).attr(\'minview\', mv);\r\n           " +
" });\r\n            $(\"[dateformat]\").each(function () {\r\n                $(this)." +
"datetimepicker({\r\n                    format: $(this).attr(\"dateformat\"),\r\n     " +
"               autoclose: true,\r\n                    language: \"zh-CN\",\r\n       " +
"             forceParse: false,\r\n                    startView: parseInt($(this)" +
".attr(\'startview\')),\r\n                    minView: parseInt($(this).attr(\'minvie" +
"w\'))\r\n                });\r\n            });\r\n");

            
            #line 152 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 152 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
             if (set.BootstrapSelect) {
            
            #line default
            #line hidden
WriteLiteral(@"
            $('.multiselect').each(function () {
                $(this).multiselect({
                    // 下拉列表仅在列表项比较多时显示过滤框
                    enableFiltering: $(this).children().length > 10,
                    buttonClass: 'btn btn-white btn-primary',
                    templates: {
                        button: '<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"multiselect dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral("></button>\',\r\n                        ul: \'<ul");

WriteLiteral(" class=\"multiselect-container dropdown-menu\"");

WriteLiteral("></ul>\',\r\n                        filter: \'<li");

WriteLiteral(" class=\"multiselect-item filter\"");

WriteLiteral("><div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral("><span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i></span><input");

WriteLiteral(" class=\"form-control multiselect-search\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("></div></li>\',\r\n                        filterClearBtn: \'<span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral("><button");

WriteLiteral(" class=\"btn btn-default btn-white btn-grey multiselect-clear-filter\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-times-circle red2\"");

WriteLiteral("></i></button></span>\',\r\n                        li: \'<li><a");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral("><label></label></a></li>\',\r\n                        divider: \'<li");

WriteLiteral(" class=\"multiselect-item divider\"");

WriteLiteral("></li>\',\r\n                        liGroup: \'<li");

WriteLiteral(" class=\"multiselect-item group\"");

WriteLiteral("><label");

WriteLiteral(" class=\"multiselect-group\"");

WriteLiteral("></label></li>\'\r\n                    },\r\n                    filterPlaceholder: \'" +
"搜索\',\r\n                    nonSelectedText: \'无\',\r\n                    allSelected" +
"Text: \'全选\'\r\n                });\r\n            });\r\n            ");

            
            #line 172 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
                   }
            
            
            #line default
            #line hidden
            
            #line 175 "..\..\Views\Shared\_Inspinia_Layout.cshtml"
                                                                                        

            
            #line default
            #line hidden
WriteLiteral(@"            $('tr').dblclick(function () {
                var $this = $(this);
                var row = $this.closest(""tr"");
                var findcell = row.find('.editcell');
                if (findcell.length > 0) window.location.href = findcell.attr(""href"");
            });
        });
    </script>

    <!--开关插件-->
    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 8004), Tuple.Create("\"", 8063)
, Tuple.Create(Tuple.Create("", 8010), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/js/plugins/switch/bootstrap-switch.min.js")
, 8010), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            $(\"input.chkSwitch" +
"\").bootstrapSwitch();\r\n        })\r\n    </script>\r\n\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 8398), Tuple.Create("\"", 8439)
, Tuple.Create(Tuple.Create("", 8404), Tuple.Create<System.Object, System.Int32>(Href("~/Templates/Cube.js?v=2.0.2017.1126")
, 8404), false)
);

WriteLiteral("></script>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
