#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_List_Data_Action.cshtml")]
    public partial class _Views_Shared__List_Data_Action_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__List_Data_Action_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_List_Data_Action.cshtml"
  
    var entity = Model as IEntity;

    var rv = entity.GetRouteKey();
    var deleteid = entity["ID"] + "";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Shared\_List_Data_Action.cshtml"
 if (this.Has(PermissionFlags.Update))
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" title=\"编辑\"");

WriteAttribute("href", Tuple.Create(" href=\"", 180), Tuple.Create("\"", 210)
            
            #line 9 "..\..\Views\Shared\_List_Data_Action.cshtml"
, Tuple.Create(Tuple.Create("", 187), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", rv)
            
            #line default
            #line hidden
, 187), false)
);

WriteLiteral(" class=\"editcell\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"fa fa-pencil\"");

WriteLiteral(" style=\"color:#1c84c6;font-size:16px;padding:0px 5px 0px 0px;\"");

WriteLiteral("></i>\r\n    </a>\r\n");

            
            #line 12 "..\..\Views\Shared\_List_Data_Action.cshtml"
}
else if (this.Has(PermissionFlags.Detail))
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" title=\"详细\"");

WriteAttribute("href", Tuple.Create(" href=\"", 408), Tuple.Create("\"", 440)
            
            #line 15 "..\..\Views\Shared\_List_Data_Action.cshtml"
, Tuple.Create(Tuple.Create("", 415), Tuple.Create<System.Object, System.Int32>(Url.Action("Detail", rv)
            
            #line default
            #line hidden
, 415), false)
);

WriteLiteral(" class=\"editcell\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"fa fa-bars\"");

WriteLiteral(" style=\"color:#1ab394;font-size:16px;padding:0px 5px 0px 5px;\"");

WriteLiteral("></i>\r\n    </a>\r\n");

            
            #line 18 "..\..\Views\Shared\_List_Data_Action.cshtml"
}

            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Shared\_List_Data_Action.cshtml"
 if (this.Has(PermissionFlags.Delete))
{
    var fact = ViewBag.Factory as IEntityOperate;
    var fi = (fact == null || fact.Fields == null) ? null : fact.Fields.FirstOrDefault(e => e.Name.EqualIgnoreCase("Deleted", "IsDelete", "IsDeleted"));
    if (fi != null && fi.Type == typeof(Boolean) && (Boolean)entity[fi.Name])
    {

            
            #line default
            #line hidden
WriteLiteral("        <i");

WriteLiteral(" class=\"glyphicon glyphicon-transfer\"");

WriteLiteral(" style=\"color: green;\"");

WriteLiteral("></i>\r\n");

WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 992), Tuple.Create("\"", 1024)
            
            #line 26 "..\..\Views\Shared\_List_Data_Action.cshtml"
, Tuple.Create(Tuple.Create("", 999), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", rv)
            
            #line default
            #line hidden
, 999), false)
);

WriteLiteral(" data-action=\"action\"");

WriteLiteral(" data-confirm=\"确认恢复？\"");

WriteLiteral(">恢复</a>\r\n");

            
            #line 27 "..\..\Views\Shared\_List_Data_Action.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("id", Tuple.Create(" id=\"", 1128), Tuple.Create("\"", 1149)
, Tuple.Create(Tuple.Create("", 1133), Tuple.Create("delete_", 1133), true)
            
            #line 30 "..\..\Views\Shared\_List_Data_Action.cshtml"
, Tuple.Create(Tuple.Create("", 1140), Tuple.Create<System.Object, System.Int32>(deleteid
            
            #line default
            #line hidden
, 1140), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 1150), Tuple.Create("\"", 1183)
            
            #line 30 "..\..\Views\Shared\_List_Data_Action.cshtml"
, Tuple.Create(Tuple.Create("", 1158), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", rv)
            
            #line default
            #line hidden
, 1158), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" title=\"删除\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1219), Tuple.Create("\"", 1252)
, Tuple.Create(Tuple.Create("", 1229), Tuple.Create("DeleteList(\'", 1229), true)
            
            #line 31 "..\..\Views\Shared\_List_Data_Action.cshtml"
, Tuple.Create(Tuple.Create("", 1241), Tuple.Create<System.Object, System.Int32>(deleteid
            
            #line default
            #line hidden
, 1241), false)
, Tuple.Create(Tuple.Create("", 1250), Tuple.Create("\')", 1250), true)
);

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-trash\"");

WriteLiteral(" style=\"color:red;font-size:16px;padding:0px 0px 0px 5px;\"");

WriteLiteral("></i>\r\n        </a>\r\n");

            
            #line 34 "..\..\Views\Shared\_List_Data_Action.cshtml"
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
