#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    #line 4 "..\..\Views\Shared\_SelectDepartment.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_SelectDepartment.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 2 "..\..\Views\Shared\_SelectDepartment.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_SelectDepartment.cshtml"
    using XCode;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_SelectDepartment.cshtml")]
    public partial class _Views_Shared__SelectDepartment_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__SelectDepartment_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\_SelectDepartment.cshtml"
  
    var id = (Object)Model + "";
    var page = ViewBag.Page as Pager;

    if (id.IsNullOrEmpty()) { id = "departmentId"; }
    var departmentId = page[id];
    var showValue = Department.FindByID(departmentId.ToInt()) + "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"position:relative\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 463), Tuple.Create("\"", 473)
            
            #line 17 "..\..\Views\Shared\_SelectDepartment.cshtml"
, Tuple.Create(Tuple.Create("", 470), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 470), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 474), Tuple.Create("\"", 482)
            
            #line 17 "..\..\Views\Shared\_SelectDepartment.cshtml"
, Tuple.Create(Tuple.Create("", 479), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 479), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 483), Tuple.Create("\"", 504)
            
            #line 17 "..\..\Views\Shared\_SelectDepartment.cshtml"
, Tuple.Create(Tuple.Create("", 491), Tuple.Create<System.Object, System.Int32>(departmentId
            
            #line default
            #line hidden
, 491), false)
);

WriteLiteral(" />\r\n            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("id", Tuple.Create(" id=\"", 561), Tuple.Create("\"", 578)
            
            #line 18 "..\..\Views\Shared\_SelectDepartment.cshtml"
, Tuple.Create(Tuple.Create("", 566), Tuple.Create<System.Object, System.Int32>(id
            
            #line default
            #line hidden
, 566), false)
, Tuple.Create(Tuple.Create("", 571), Tuple.Create("_select", 571), true)
);

WriteLiteral(" placeholder=\"搜索部门\"");

WriteAttribute("value", Tuple.Create(" value=\"", 598), Tuple.Create("\"", 616)
            
            #line 18 "..\..\Views\Shared\_SelectDepartment.cshtml"
                 , Tuple.Create(Tuple.Create("", 606), Tuple.Create<System.Object, System.Int32>(showValue
            
            #line default
            #line hidden
, 606), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-right\"");

WriteLiteral(" role=\"menu\"");

WriteLiteral("></ul>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 809), Tuple.Create("\"", 845)
, Tuple.Create(Tuple.Create("", 815), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap-suggest.js")
, 815), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(function () {\r\n        $(\"#");

            
            #line 29 "..\..\Views\Shared\_SelectDepartment.cshtml"
        Write(id);

            
            #line default
            #line hidden
WriteLiteral(@"_select"").bsSuggest({
            url: ""/cube/DepartmentSearch?key="",
            getDataMethod:""url"",
            effectiveFieldsAlias: { ID:""编号"",Code:""代码"",Name: ""名称"",FullName:'全名',Manager:'管理者'},
            ignorecase: true,
            showHeader: true,
            delayUntilKeyup: true, //获取数据的方式为 firstByUrl 时，延迟到有输入/获取到焦点时才请求数据
            hideOnSelect: true,
            idField: ""ID"",
            showBtn: false,
            keyField: ""Name"",
            clearable: true,
            searchingTip: '搜索中...',
            allowNoKeyword: true,
            delay: 500,
            emptyTip: '无数据',
            containerValueId: '");

            
            #line 45 "..\..\Views\Shared\_SelectDepartment.cshtml"
                          Write(id);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            fnProcessData: function (result) {\r\n                dt = {};\r\n   " +
"             dt.value = result.data;\r\n                return dt;\r\n            }\r" +
"\n        }).on(\'onSetSelectValue\', function (e, keyword, data) {\r\n            $(" +
"\'#");

            
            #line 52 "..\..\Views\Shared\_SelectDepartment.cshtml"
           Write(id);

            
            #line default
            #line hidden
WriteLiteral("\').val(keyword.id);\r\n        }).on(\'onUnsetSelectValue\', function () {\r\n         " +
"   $(\'#");

            
            #line 54 "..\..\Views\Shared\_SelectDepartment.cshtml"
           Write(id);

            
            #line default
            #line hidden
WriteLiteral("\').val(\'\');\r\n        });\r\n    });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
