#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CubeDemo;
    
    #line 1 "..\..\Areas\School\Views\Student\_List_Search.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 4 "..\..\Areas\School\Views\Student\_List_Search.cshtml"
    using NewLife.School.Entity;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\School\Views\Student\_List_Search.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\School\Views\Student\_List_Search.cshtml"
    using XCode;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/School/Views/Student/_List_Search.cshtml")]
    public partial class _Areas_School_Views_Student__List_Search_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_School_Views_Student__List_Search_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Areas\School\Views\Student\_List_Search.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"RoleID\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">班级：</label>\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Areas\School\Views\Student\_List_Search.cshtml"
Write(Html.ForDropDownList("ClassID", Class.FindAllWithCache().Cast<IEntity>().ToList(), "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
