#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Areas\Admin\Views\File\Index.cshtml"
    using System.Diagnostics;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    
    #line 2 "..\..\Areas\Admin\Views\File\Index.cshtml"
    using NewLife.Common;
    
    #line default
    #line hidden
    using NewLife.Cube;
    
    #line 3 "..\..\Areas\Admin\Views\File\Index.cshtml"
    using NewLife.Cube.Admin;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/File/Index.cshtml")]
    public partial class _Areas_Admin_Views_File_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_File_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\File\Index.cshtml"
  
    var fs = Model as List<FileItem>;
    var r = ViewBag.Current as String;
    var clips = ViewBag.Clip as ICollection<FileItem>;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n    <form");

WriteAttribute("action", Tuple.Create(" action=\"", 258), Tuple.Create("\"", 279)
, Tuple.Create(Tuple.Create("", 267), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File")
, 267), false)
);

WriteLiteral(" id=\"tool\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"ace-icon fa fa-check\"");

WriteLiteral("></i>\r\n            </span>\r\n            <input");

WriteLiteral(" name=\"r\"");

WriteLiteral(" type=\"search\"");

WriteLiteral(" id=\"r\"");

WriteAttribute("value", Tuple.Create(" value=\"", 511), Tuple.Create("\"", 521)
            
            #line 15 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 519), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 519), false)
);

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"目标路径\"");

WriteLiteral(" />\r\n            <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-folder-open icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                    打开\r\n                </button>\r\n            </span>\r" +
"\n        </div>\r\n        <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" name=\"ufile\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ufile\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"文件\"");

WriteLiteral(" />\r\n            <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" onclick=\"$(\'input[id=file]\').click();\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-cloud-upload icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                    选择文件\r\n                </button>\r\n            </span" +
">\r\n            <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" style=\"margin-left:5px;\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" onclick=\"$(\'#tool\').attr(\'action\', \'/Admin/File/Upload\');$(\'#tool\').attr(\'enctyp" +
"e\', \'multipart/form-data\'); return true;\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-plus icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                    上传\r\n                </button>\r\n            </span>\r" +
"\n        </div>\r\n        <div");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">    <input");

WriteLiteral(" name=\"file\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"file\"");

WriteLiteral(" placeholder=\"上传文件\"");

WriteLiteral(" onchange=\"$(\'#ufile\').val($(\'input[id=file]\').val());\"");

WriteLiteral(" /></div>\r\n");

            
            #line 39 "..\..\Areas\Admin\Views\File\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Areas\Admin\Views\File\Index.cshtml"
         if (clips.Count > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"glyphicon glyphicon-floppy-disk\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2140), Tuple.Create("\"", 2168)
, Tuple.Create(Tuple.Create("", 2148), Tuple.Create("剪切板共有", 2148), true)
            
            #line 43 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create(" ", 2153), Tuple.Create<System.Object, System.Int32>(clips.Count
            
            #line default
            #line hidden
, 2154), false)
, Tuple.Create(Tuple.Create(" ", 2166), Tuple.Create("项", 2167), true)
);

WriteLiteral(">");

            
            #line 43 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                                                                       Write(clips.Count);

            
            #line default
            #line hidden
WriteLiteral("</i>\r\n                </span>\r\n                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-pink btn-sm\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2330), Tuple.Create("\"", 2381)
, Tuple.Create(Tuple.Create("", 2340), Tuple.Create("location.href", 2340), true)
, Tuple.Create(Tuple.Create(" ", 2353), Tuple.Create("=", 2354), true)
, Tuple.Create(Tuple.Create(" ", 2355), Tuple.Create("\'/Admin/File/Paste?r=", 2356), true)
            
            #line 46 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                    , Tuple.Create(Tuple.Create("", 2377), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 2377), false)
, Tuple.Create(Tuple.Create("", 2379), Tuple.Create("\';", 2379), true)
);

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"glyphicon glyphicon-floppy-save icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                        粘贴\r\n                    </button>\r\n            " +
"    </span>\r\n                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-gray btn-sm\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2690), Tuple.Create("\"", 2740)
, Tuple.Create(Tuple.Create("", 2700), Tuple.Create("location.href", 2700), true)
, Tuple.Create(Tuple.Create(" ", 2713), Tuple.Create("=", 2714), true)
, Tuple.Create(Tuple.Create(" ", 2715), Tuple.Create("\'/Admin/File/Move?r=", 2716), true)
            
            #line 52 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                   , Tuple.Create(Tuple.Create("", 2736), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 2736), false)
, Tuple.Create(Tuple.Create("", 2738), Tuple.Create("\';", 2738), true)
);

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"glyphicon glyphicon-floppy-save icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                        移动\r\n                    </button>\r\n            " +
"    </span>\r\n                <span");

WriteLiteral(" class=\"input-group-btn\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-yellow btn-sm\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 3051), Tuple.Create("\"", 3111)
, Tuple.Create(Tuple.Create("", 3061), Tuple.Create("location.href", 3061), true)
, Tuple.Create(Tuple.Create(" ", 3074), Tuple.Create("=", 3075), true)
, Tuple.Create(Tuple.Create(" ", 3076), Tuple.Create("\'/Admin/File/ClearClipboard?r=", 3077), true)
            
            #line 58 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                               , Tuple.Create(Tuple.Create("", 3107), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 3107), false)
, Tuple.Create(Tuple.Create("", 3109), Tuple.Create("\';", 3109), true)
);

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"glyphicon glyphicon-retweet icon-on-right bigger-110\"");

WriteLiteral("></span>\r\n                        清空\r\n                    </button>\r\n            " +
"    </span>\r\n            </div>\r\n");

            
            #line 64 "..\..\Areas\Admin\Views\File\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </form>\r\n</div>\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3496), Tuple.Create("\"", 3530)
, Tuple.Create(Tuple.Create("", 3503), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File?r=")
, 3503), false)
            
            #line 70 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3518), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 3518), false)
, Tuple.Create(Tuple.Create("", 3520), Tuple.Create("&sort=name", 3520), true)
);

WriteLiteral(">名称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3583), Tuple.Create("\"", 3617)
, Tuple.Create(Tuple.Create("", 3590), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File?r=")
, 3590), false)
            
            #line 71 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3605), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 3605), false)
, Tuple.Create(Tuple.Create("", 3607), Tuple.Create("&sort=size", 3607), true)
);

WriteLiteral(">大小</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3670), Tuple.Create("\"", 3709)
, Tuple.Create(Tuple.Create("", 3677), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File?r=")
, 3677), false)
            
            #line 72 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3692), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 3692), false)
, Tuple.Create(Tuple.Create("", 3694), Tuple.Create("&sort=lastwrite", 3694), true)
);

WriteLiteral(">修改时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">复制</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">压缩</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">删除</th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 79 "..\..\Areas\Admin\Views\File\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 79 "..\..\Areas\Admin\Views\File\Index.cshtml"
         foreach (var item in fs)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 82 "..\..\Areas\Admin\Views\File\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 82 "..\..\Areas\Admin\Views\File\Index.cshtml"
                 if (item.Directory)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td>&nbsp;&nbsp;<a");

WriteAttribute("href", Tuple.Create(" href=\"", 4062), Tuple.Create("\"", 4098)
, Tuple.Create(Tuple.Create("", 4069), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File?r=")
, 4069), false)
            
            #line 84 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4084), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 4084), false)
);

WriteLiteral(" title=\"进入目录\"");

WriteLiteral(">");

            
            #line 84 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                                                                    Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n");

            
            #line 85 "..\..\Areas\Admin\Views\File\Index.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td>&nbsp;&nbsp;<a");

WriteAttribute("href", Tuple.Create(" href=\"", 4232), Tuple.Create("\"", 4277)
, Tuple.Create(Tuple.Create("", 4239), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/Download?r=")
, 4239), false)
            
            #line 88 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4263), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 4263), false)
);

WriteLiteral(" title=\"下载文件\"");

WriteLiteral(">");

            
            #line 88 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                                                                             Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n");

            
            #line 89 "..\..\Areas\Admin\Views\File\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 90 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                  Write(item.Size);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 91 "..\..\Areas\Admin\Views\File\Index.cshtml"
                                   Write(item.LastWrite.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

            
            #line 93 "..\..\Areas\Admin\Views\File\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 93 "..\..\Areas\Admin\Views\File\Index.cshtml"
                     if (!clips.Any(e => e.FullName == item.FullName))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4630), Tuple.Create("\"", 4676)
, Tuple.Create(Tuple.Create("", 4637), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/Copy?r=")
, 4637), false)
            
            #line 95 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4657), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 4657), false)
, Tuple.Create(Tuple.Create("", 4659), Tuple.Create("&f=", 4659), true)
            
            #line 95 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4662), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 4662), false)
);

WriteLiteral(" title=\"复制到剪切板，然后去目标目录粘贴\"");

WriteLiteral(">复制</a>\r\n");

            
            #line 96 "..\..\Areas\Admin\Views\File\Index.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4809), Tuple.Create("\"", 4861)
, Tuple.Create(Tuple.Create("", 4816), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/CancelCopy?r=")
, 4816), false)
            
            #line 99 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4842), Tuple.Create<System.Object, System.Int32>(r
            
            #line default
            #line hidden
, 4842), false)
, Tuple.Create(Tuple.Create("", 4844), Tuple.Create("&f=", 4844), true)
            
            #line 99 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 4847), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 4847), false)
);

WriteLiteral(" title=\"从剪切板移除\"");

WriteLiteral(">取消复制</a>\r\n");

            
            #line 100 "..\..\Areas\Admin\Views\File\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n");

            
            #line 102 "..\..\Areas\Admin\Views\File\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 102 "..\..\Areas\Admin\Views\File\Index.cshtml"
                 if (item.Name.EndsWithIgnoreCase(".zip"))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5059), Tuple.Create("\"", 5106)
, Tuple.Create(Tuple.Create("", 5066), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/Decompress?r=")
, 5066), false)
            
            #line 104 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5092), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 5092), false)
);

WriteLiteral(" title=\"解压缩到当前目录\"");

WriteLiteral(">解压缩</a></td>\r\n");

            
            #line 105 "..\..\Areas\Admin\Views\File\Index.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5245), Tuple.Create("\"", 5290)
, Tuple.Create(Tuple.Create("", 5252), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/Compress?r=")
, 5252), false)
            
            #line 108 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5276), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 5276), false)
);

WriteLiteral(" title=\"压缩到当前目录，加上时间后缀\"");

WriteLiteral(">压缩</a></td>\r\n");

            
            #line 109 "..\..\Areas\Admin\Views\File\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5389), Tuple.Create("\"", 5432)
, Tuple.Create(Tuple.Create("", 5396), Tuple.Create<System.Object, System.Int32>(Href("~/Admin/File/Delete?r=")
, 5396), false)
            
            #line 110 "..\..\Areas\Admin\Views\File\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5418), Tuple.Create<System.Object, System.Int32>(item.FullName
            
            #line default
            #line hidden
, 5418), false)
);

WriteLiteral(" onclick=\"return confirm(\'确认删除？\');\"");

WriteLiteral(">删除</a></td>\r\n            </tr>\r\n");

            
            #line 112 "..\..\Areas\Admin\Views\File\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
