#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Log/_List_Data.cshtml")]
    public partial class _Areas_Admin_Views_Log__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<XCode.Membership.Log>>
    {
        public _Areas_Admin_Views_Log__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityFactory;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var set = ViewBag.PageSetting as PageSetting;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
             if (set.EnableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 756), Tuple.Create("\"", 795)
            
            #line 23 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 763), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 763), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 848), Tuple.Create("\"", 893)
            
            #line 24 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 855), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Category"))
            
            #line default
            #line hidden
, 855), false)
);

WriteLiteral(">类别</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 946), Tuple.Create("\"", 989)
            
            #line 25 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 953), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Action"))
            
            #line default
            #line hidden
, 953), false)
);

WriteLiteral(">操作</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1042), Tuple.Create("\"", 1086)
            
            #line 26 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1049), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Success"))
            
            #line default
            #line hidden
, 1049), false)
);

WriteLiteral(">成功</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1139), Tuple.Create("\"", 1182)
            
            #line 27 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1146), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Remark"))
            
            #line default
            #line hidden
, 1146), false)
);

WriteLiteral(">详细信息</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1237), Tuple.Create("\"", 1280)
            
            #line 28 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1244), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("LinkID"))
            
            #line default
            #line hidden
, 1244), false)
);

WriteLiteral(">链接</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1333), Tuple.Create("\"", 1378)
            
            #line 29 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1340), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UserName"))
            
            #line default
            #line hidden
, 1340), false)
);

WriteLiteral(">用户名</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1432), Tuple.Create("\"", 1477)
            
            #line 30 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1439), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("CreateIP"))
            
            #line default
            #line hidden
, 1439), false)
);

WriteLiteral(">IP地址</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1532), Tuple.Create("\"", 1582)
            
            #line 31 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1539), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("CreateAddress"))
            
            #line default
            #line hidden
, 1539), false)
);

WriteLiteral(">物理地址</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1662), Tuple.Create("\"", 1709)
            
            #line 32 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1669), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("CreateTime"))
            
            #line default
            #line hidden
, 1669), false)
);

WriteLiteral(">时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">附近</th>\r\n");

            
            #line 34 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 34 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 37 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 41 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 41 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
         foreach (var entity in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 44 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                 if (set.EnableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2148), Tuple.Create("\"", 2166)
            
            #line 46 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 2156), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2156), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 47 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 48 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                                   Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 49 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
               Write(entity.Category);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 50 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
               Write(entity.Action);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 2401), Tuple.Create("\"", 2464)
, Tuple.Create(Tuple.Create("", 2409), Tuple.Create("glyphicon", 2409), true)
, Tuple.Create(Tuple.Create(" ", 2418), Tuple.Create("glyphicon-", 2419), true)
            
            #line 52 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2429), Tuple.Create<System.Object, System.Int32>(entity.Success ? "ok" : "remove"
            
            #line default
            #line hidden
, 2429), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 2465), Tuple.Create("\"", 2516)
, Tuple.Create(Tuple.Create("", 2473), Tuple.Create("color:", 2473), true)
            
            #line 52 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                     , Tuple.Create(Tuple.Create(" ", 2479), Tuple.Create<System.Object, System.Int32>(entity.Success ? "green" : "red"
            
            #line default
            #line hidden
, 2480), false)
, Tuple.Create(Tuple.Create("", 2515), Tuple.Create(";", 2515), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" style=\"max-width:600px;overflow:hidden;white-space: nowrap;text-overflow: ellips" +
"is;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2651), Tuple.Create("\"", 2673)
            
            #line 54 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                                , Tuple.Create(Tuple.Create("", 2659), Tuple.Create<System.Object, System.Int32>(entity.Remark
            
            #line default
            #line hidden
, 2659), false)
);

WriteLiteral(">");

            
            #line 54 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                                                                                                                           Write(entity.Remark);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 55 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                                  Write(entity.LinkID.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 56 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
               Write(entity.UserName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 57 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
               Write(entity.CreateIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 58 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
               Write(entity.CreateIP.IPToAddress());

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"max-width:150px\"");

WriteLiteral(">");

            
            #line 59 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                                                           Write(entity.CreateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3084), Tuple.Create("\"", 3123)
, Tuple.Create(Tuple.Create("", 3091), Tuple.Create("?act=near&id=", 3091), true)
            
            #line 61 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3104), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 3104), false)
, Tuple.Create(Tuple.Create("", 3114), Tuple.Create("&range=10", 3114), true)
);

WriteLiteral(" title=\"前后10行日志\"");

WriteLiteral(">附近</a>\r\n                </td>\r\n");

            
            #line 63 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 63 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width: 90px;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 66 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 68 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 70 "..\..\Areas\Admin\Views\Log\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
