#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/_List_Data.cshtml")]
    public partial class _Areas_Admin_Views_User__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<XCode.Membership.UserX>>
    {
        public _Areas_Admin_Views_User__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var set = ViewBag.PageSetting as PageSetting;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
             if (set.EnableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 758), Tuple.Create("\"", 797)
            
            #line 23 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 765), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 765), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"名称。登录用户名\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 867), Tuple.Create("\"", 908)
            
            #line 24 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 874), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Name"))
            
            #line default
            #line hidden
, 874), false)
);

WriteLiteral(">名称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 961), Tuple.Create("\"", 1009)
            
            #line 25 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 968), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("DisplayName"))
            
            #line default
            #line hidden
, 968), false)
);

WriteLiteral(">昵称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"性别。未知、男、女\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1080), Tuple.Create("\"", 1120)
            
            #line 26 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1087), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Sex"))
            
            #line default
            #line hidden
, 1087), false)
);

WriteLiteral(">性别</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1173), Tuple.Create("\"", 1214)
            
            #line 27 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1180), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Mail"))
            
            #line default
            #line hidden
, 1180), false)
);

WriteLiteral(">邮件</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1267), Tuple.Create("\"", 1310)
            
            #line 28 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1274), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Mobile"))
            
            #line default
            #line hidden
, 1274), false)
);

WriteLiteral(">手机</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1363), Tuple.Create("\"", 1412)
            
            #line 29 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1370), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("DepartmentID"))
            
            #line default
            #line hidden
, 1370), false)
);

WriteLiteral(">部门</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1465), Tuple.Create("\"", 1508)
            
            #line 30 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1472), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("RoleID"))
            
            #line default
            #line hidden
, 1472), false)
);

WriteLiteral(">角色</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1561), Tuple.Create("\"", 1604)
            
            #line 31 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1568), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Online"))
            
            #line default
            #line hidden
, 1568), false)
);

WriteLiteral(">在线</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1657), Tuple.Create("\"", 1700)
            
            #line 32 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1664), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Enable"))
            
            #line default
            #line hidden
, 1664), false)
);

WriteLiteral(">启用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1753), Tuple.Create("\"", 1796)
            
            #line 33 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1760), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Logins"))
            
            #line default
            #line hidden
, 1760), false)
);

WriteLiteral(">登录次数</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1876), Tuple.Create("\"", 1922)
            
            #line 34 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1883), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("LastLogin"))
            
            #line default
            #line hidden
, 1883), false)
);

WriteLiteral(">最后登录</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1977), Tuple.Create("\"", 2025)
            
            #line 35 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1984), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("LastLoginIP"))
            
            #line default
            #line hidden
, 1984), false)
);

WriteLiteral(">最后IP</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">链接</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">日志</th>\r\n");

            
            #line 38 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 38 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:100px;\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 41 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 45 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
         foreach (var entity in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 48 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 48 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                 if (set.EnableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2584), Tuple.Create("\"", 2602)
            
            #line 50 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 2592), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2592), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 51 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 52 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                   Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 53 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 54 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 55 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                   Write(entity.Sex);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 56 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.Mail);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 57 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.Mobile);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2934), Tuple.Create("\"", 2975)
, Tuple.Create(Tuple.Create("", 2941), Tuple.Create("Department?ID=", 2941), true)
            
            #line 58 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2955), Tuple.Create<System.Object, System.Int32>(entity.DepartmentID
            
            #line default
            #line hidden
, 2955), false)
);

WriteLiteral(">");

            
            #line 58 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                                            Write(entity.DepartmentName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3032), Tuple.Create("\"", 3061)
, Tuple.Create(Tuple.Create("", 3039), Tuple.Create("Role?ID=", 3039), true)
            
            #line 59 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3047), Tuple.Create<System.Object, System.Int32>(entity.RoleID
            
            #line default
            #line hidden
, 3047), false)
);

WriteLiteral(">");

            
            #line 59 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                                Write(entity.RoleName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3154), Tuple.Create("\"", 3216)
, Tuple.Create(Tuple.Create("", 3162), Tuple.Create("glyphicon", 3162), true)
, Tuple.Create(Tuple.Create(" ", 3171), Tuple.Create("glyphicon-", 3172), true)
            
            #line 61 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3182), Tuple.Create<System.Object, System.Int32>(entity.Online ? "ok" : "remove"
            
            #line default
            #line hidden
, 3182), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 3217), Tuple.Create("\"", 3267)
, Tuple.Create(Tuple.Create("", 3225), Tuple.Create("color:", 3225), true)
            
            #line 61 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                    , Tuple.Create(Tuple.Create(" ", 3231), Tuple.Create<System.Object, System.Int32>(entity.Online ? "green" : "red"
            
            #line default
            #line hidden
, 3232), false)
, Tuple.Create(Tuple.Create("", 3266), Tuple.Create(";", 3266), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3362), Tuple.Create("\"", 3424)
, Tuple.Create(Tuple.Create("", 3370), Tuple.Create("glyphicon", 3370), true)
, Tuple.Create(Tuple.Create(" ", 3379), Tuple.Create("glyphicon-", 3380), true)
            
            #line 64 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3390), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "ok" : "remove"
            
            #line default
            #line hidden
, 3390), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 3425), Tuple.Create("\"", 3475)
, Tuple.Create(Tuple.Create("", 3433), Tuple.Create("color:", 3433), true)
            
            #line 64 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                    , Tuple.Create(Tuple.Create(" ", 3439), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "green" : "red"
            
            #line default
            #line hidden
, 3440), false)
, Tuple.Create(Tuple.Create("", 3474), Tuple.Create(";", 3474), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 66 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                  Write(entity.Logins.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 67 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.LastLogin.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 3661), Tuple.Create("\"", 3693)
            
            #line 68 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3669), Tuple.Create<System.Object, System.Int32>(entity.LastLoginAddress
            
            #line default
            #line hidden
, 3669), false)
);

WriteLiteral(">");

            
            #line 68 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                                Write(entity.LastLoginIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 69 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(Html.ActionLink("链接", "Index", "UserConnect", new { UserID = entity.ID }, null));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 70 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(Html.ActionLink("日志", "Index", "Log", new { UserID = entity.ID }, null));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 71 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 71 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 74 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 76 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 78 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
