#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    
    #line 6 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Mvc.Ajax;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Mvc.Html;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using System.Web.Routing;
    
    #line default
    #line hidden
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 3 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/_List_Data.cshtml")]
    public partial class _Areas_Admin_Views_User__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<XCode.Membership.UserX>>
    {
        public _Areas_Admin_Views_User__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 10 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var enableSelect = this.EnableSelect();
    //var provider = ManageProvider.Provider;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 20 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
             if (enableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 23 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 825), Tuple.Create("\"", 864)
            
            #line 24 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 832), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 832), false)
);

WriteLiteral(">编号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"名称。登录用户名\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 934), Tuple.Create("\"", 975)
            
            #line 25 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 941), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Name"))
            
            #line default
            #line hidden
, 941), false)
);

WriteLiteral(">名称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1028), Tuple.Create("\"", 1076)
            
            #line 26 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1035), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("DisplayName"))
            
            #line default
            #line hidden
, 1035), false)
);

WriteLiteral(">昵称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"性别。未知、男、女\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1147), Tuple.Create("\"", 1187)
            
            #line 27 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1154), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Sex"))
            
            #line default
            #line hidden
, 1154), false)
);

WriteLiteral(">性别</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1240), Tuple.Create("\"", 1281)
            
            #line 28 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1247), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Mail"))
            
            #line default
            #line hidden
, 1247), false)
);

WriteLiteral(">邮件</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1334), Tuple.Create("\"", 1377)
            
            #line 29 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1341), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Mobile"))
            
            #line default
            #line hidden
, 1341), false)
);

WriteLiteral(">手机</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1430), Tuple.Create("\"", 1479)
            
            #line 30 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1437), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("DepartmentID"))
            
            #line default
            #line hidden
, 1437), false)
);

WriteLiteral(">部门</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1532), Tuple.Create("\"", 1575)
            
            #line 31 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1539), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("RoleID"))
            
            #line default
            #line hidden
, 1539), false)
);

WriteLiteral(">角色</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1628), Tuple.Create("\"", 1671)
            
            #line 32 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1635), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Online"))
            
            #line default
            #line hidden
, 1635), false)
);

WriteLiteral(">在线</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1724), Tuple.Create("\"", 1767)
            
            #line 33 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1731), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Enable"))
            
            #line default
            #line hidden
, 1731), false)
);

WriteLiteral(">启用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1820), Tuple.Create("\"", 1863)
            
            #line 34 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1827), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Logins"))
            
            #line default
            #line hidden
, 1827), false)
);

WriteLiteral(">登录次数</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1943), Tuple.Create("\"", 1989)
            
            #line 35 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1950), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("LastLogin"))
            
            #line default
            #line hidden
, 1950), false)
);

WriteLiteral(">最后登录</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2044), Tuple.Create("\"", 2092)
            
            #line 36 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2051), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("LastLoginIP"))
            
            #line default
            #line hidden
, 2051), false)
);

WriteLiteral(">最后IP</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">日志</th>\r\n");

            
            #line 38 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 38 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:100px;\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 41 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 45 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
         foreach (var entity in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 48 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 48 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                 if (enableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2602), Tuple.Create("\"", 2620)
            
            #line 50 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 2610), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2610), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 51 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center hidden-md hidden-sm hidden-xs\"");

WriteLiteral(">");

            
            #line 52 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                                                 Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 53 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 54 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 55 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                   Write(entity.Sex);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 56 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.Mail);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 57 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.Mobile);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2982), Tuple.Create("\"", 3023)
, Tuple.Create(Tuple.Create("", 2989), Tuple.Create("Department?ID=", 2989), true)
            
            #line 58 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3003), Tuple.Create<System.Object, System.Int32>(entity.DepartmentID
            
            #line default
            #line hidden
, 3003), false)
);

WriteLiteral(">");

            
            #line 58 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                                            Write(entity.DepartmentName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3080), Tuple.Create("\"", 3109)
, Tuple.Create(Tuple.Create("", 3087), Tuple.Create("Role?ID=", 3087), true)
            
            #line 59 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3095), Tuple.Create<System.Object, System.Int32>(entity.RoleID
            
            #line default
            #line hidden
, 3095), false)
);

WriteLiteral(">");

            
            #line 59 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                                Write(entity.RoleName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3202), Tuple.Create("\"", 3264)
, Tuple.Create(Tuple.Create("", 3210), Tuple.Create("glyphicon", 3210), true)
, Tuple.Create(Tuple.Create(" ", 3219), Tuple.Create("glyphicon-", 3220), true)
            
            #line 61 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3230), Tuple.Create<System.Object, System.Int32>(entity.Online ? "ok" : "remove"
            
            #line default
            #line hidden
, 3230), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 3265), Tuple.Create("\"", 3315)
, Tuple.Create(Tuple.Create("", 3273), Tuple.Create("color:", 3273), true)
            
            #line 61 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                    , Tuple.Create(Tuple.Create(" ", 3279), Tuple.Create<System.Object, System.Int32>(entity.Online ? "green" : "red"
            
            #line default
            #line hidden
, 3280), false)
, Tuple.Create(Tuple.Create("", 3314), Tuple.Create(";", 3314), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3410), Tuple.Create("\"", 3472)
, Tuple.Create(Tuple.Create("", 3418), Tuple.Create("glyphicon", 3418), true)
, Tuple.Create(Tuple.Create(" ", 3427), Tuple.Create("glyphicon-", 3428), true)
            
            #line 64 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3438), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "ok" : "remove"
            
            #line default
            #line hidden
, 3438), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 3473), Tuple.Create("\"", 3523)
, Tuple.Create(Tuple.Create("", 3481), Tuple.Create("color:", 3481), true)
            
            #line 64 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                    , Tuple.Create(Tuple.Create(" ", 3487), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "green" : "red"
            
            #line default
            #line hidden
, 3488), false)
, Tuple.Create(Tuple.Create("", 3522), Tuple.Create(";", 3522), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 66 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                  Write(entity.Logins.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 67 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(entity.LastLogin.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteAttribute("title", Tuple.Create(" title=\"", 3709), Tuple.Create("\"", 3741)
            
            #line 68 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3717), Tuple.Create<System.Object, System.Int32>(entity.LastLoginAddress
            
            #line default
            #line hidden
, 3717), false)
);

WriteLiteral(">");

            
            #line 68 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                                                Write(entity.LastLoginIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 69 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
               Write(Html.ActionLink("日志", "Index", "Log", new { UserID = entity.ID }, null));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 70 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 70 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 73 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 75 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 77 "..\..\Areas\Admin\Views\User\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
