#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/_User_Nav.cshtml")]
    public partial class _Areas_Admin_Views_User__User_Nav_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_User__User_Nav_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"text-center col-md-12\"");

WriteLiteral(" style=\"margin-bottom: 10px\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 2 "..\..\Areas\Admin\Views\User\_User_Nav.cshtml"
Write(Html.ActionLink("基本信息", "Info", "User", null, new { @class = "btn btn-success btn-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 3 "..\..\Areas\Admin\Views\User\_User_Nav.cshtml"
Write(Html.ActionLink("修改密码", "ChangePassword", "User", null, new { @class = "btn btn-success btn-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 4 "..\..\Areas\Admin\Views\User\_User_Nav.cshtml"
Write(Html.ActionLink("第三方授权", "Binds", "User", null, new { @class = "btn btn-success btn-sm" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
