#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    #line 2 "..\..\Areas\Admin\Views\User\Binds.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    
    #line 3 "..\..\Areas\Admin\Views\User\Binds.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    
    #line 7 "..\..\Areas\Admin\Views\User\Binds.cshtml"
    using NewLife.Cube.Areas.Admin.Models;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Areas\Admin\Views\User\Binds.cshtml"
    using NewLife.Cube.Entity;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    
    #line 4 "..\..\Areas\Admin\Views\User\Binds.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Admin\Views\User\Binds.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/Binds.cshtml")]
    public partial class _Areas_Admin_Views_User_Binds_cshtml : System.Web.Mvc.WebViewPage<BindsModel>
    {
        public _Areas_Admin_Views_User_Binds_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 8 "..\..\Areas\Admin\Views\User\Binds.cshtml"
  
    var ms = Model.OAuthItems;
    var binds = Model.Connects;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Areas\Admin\Views\User\Binds.cshtml"
Write(Html.Partial("_User_Nav"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">名称</label>\r\n                <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n                    <input");

WriteAttribute("value", Tuple.Create(" value=\"", 577), Tuple.Create("\"", 596)
            
            #line 21 "..\..\Areas\Admin\Views\User\Binds.cshtml"
, Tuple.Create(Tuple.Create("", 585), Tuple.Create<System.Object, System.Int32>(Model.Name
            
            #line default
            #line hidden
, 585), false)
);

WriteLiteral(" class=\"col-xs-12 col-sm-8 col-md-6 col-lg-4\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n");

            
            #line 24 "..\..\Areas\Admin\Views\User\Binds.cshtml"
            
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\Admin\Views\User\Binds.cshtml"
             if (ms.Count > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">第三方绑定</label>\r\n                    <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n                        <ul>\r\n");

            
            #line 30 "..\..\Areas\Admin\Views\User\Binds.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Admin\Views\User\Binds.cshtml"
                             foreach (var mi in ms)
                            {
                                var uc = binds.FirstOrDefault(e => e.Enable && e.Provider.EqualIgnoreCase(mi.Name));
                                if (uc != null)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>\r\n                                       " +
" <span>");

            
            #line 36 "..\..\Areas\Admin\Views\User\Binds.cshtml"
                                         Write(mi.Name);

            
            #line default
            #line hidden
WriteLiteral("（已绑定）</span>\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1397), Tuple.Create("\"", 1425)
, Tuple.Create(Tuple.Create("", 1404), Tuple.Create<System.Object, System.Int32>(Href("~/Sso/UnBind/")
, 1404), false)
            
            #line 37 "..\..\Areas\Admin\Views\User\Binds.cshtml"
, Tuple.Create(Tuple.Create("", 1417), Tuple.Create<System.Object, System.Int32>(mi.Name
            
            #line default
            #line hidden
, 1417), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1426), Tuple.Create("\"", 1447)
, Tuple.Create(Tuple.Create("", 1434), Tuple.Create("取消绑定", 1434), true)
            
            #line 37 "..\..\Areas\Admin\Views\User\Binds.cshtml"
   , Tuple.Create(Tuple.Create(" ", 1438), Tuple.Create<System.Object, System.Int32>(mi.Name
            
            #line default
            #line hidden
, 1439), false)
);

WriteLiteral(">取消绑定</a>\r\n                                    </li>\r\n");

            
            #line 39 "..\..\Areas\Admin\Views\User\Binds.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>\r\n                                       " +
" <span>");

            
            #line 43 "..\..\Areas\Admin\Views\User\Binds.cshtml"
                                         Write(mi.Name);

            
            #line default
            #line hidden
WriteLiteral("（未绑定）</span>\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1762), Tuple.Create("\"", 1788)
, Tuple.Create(Tuple.Create("", 1769), Tuple.Create<System.Object, System.Int32>(Href("~/Sso/Bind/")
, 1769), false)
            
            #line 44 "..\..\Areas\Admin\Views\User\Binds.cshtml"
, Tuple.Create(Tuple.Create("", 1780), Tuple.Create<System.Object, System.Int32>(mi.Name
            
            #line default
            #line hidden
, 1780), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1789), Tuple.Create("\"", 1808)
, Tuple.Create(Tuple.Create("", 1797), Tuple.Create("绑定", 1797), true)
            
            #line 44 "..\..\Areas\Admin\Views\User\Binds.cshtml"
, Tuple.Create(Tuple.Create(" ", 1799), Tuple.Create<System.Object, System.Int32>(mi.Name
            
            #line default
            #line hidden
, 1800), false)
);

WriteLiteral(">去绑定</a>\r\n                                    </li>\r\n");

            
            #line 46 "..\..\Areas\Admin\Views\User\Binds.cshtml"
                                }
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </div>\r\n                </div>" +
"\r\n");

            
            #line 51 "..\..\Areas\Admin\Views\User\Binds.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
