#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using NewLife;
    using NewLife.Cube;
    
    #line 2 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
    using NewLife.Cube.Areas.Admin.Models;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/User/ChangePassword.cshtml")]
    public partial class _Areas_Admin_Views_User_ChangePassword_cshtml : System.Web.Mvc.WebViewPage<ChangePasswordModel>
    {
        public _Areas_Admin_Views_User_ChangePassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
  
    var requireOldPass = String.IsNullOrEmpty(Model.SsoName);

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 7 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
Write(Html.Partial("_User_Nav"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
            
            
            #line default
            #line hidden
            
            #line 12 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
             if (ViewBag.StatusMessage != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"alert alert-success alert-dismissible text-center\"");

WriteLiteral(" role=\"alert\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"success\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span></button>\r\n                    <strong>");

            
            #line 16 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
                       Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                </div>\r\n");

            
            #line 18 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 19 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
             using (Html.BeginForm("ChangePassword", "User"))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">名称</label>\r\n                    <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n                        <input");

WriteAttribute("value", Tuple.Create(" value=\"", 967), Tuple.Create("\"", 986)
            
            #line 24 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
, Tuple.Create(Tuple.Create("", 975), Tuple.Create<System.Object, System.Int32>(Model.Name
            
            #line default
            #line hidden
, 975), false)
);

WriteLiteral(" class=\"col-xs-12 col-sm-8 col-md-6 col-lg-4\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" />\r\n");

            
            #line 25 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 25 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
                         if (!String.IsNullOrEmpty(Model.SsoName))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <label>登录自 ");

            
            #line 27 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
                                  Write(Model.SsoName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

            
            #line 28 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </div>\r\n");

            
            #line 31 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
                if (requireOldPass)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">原密码</label>\r\n                        <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" name=\"OldPassword\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 39 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">新密码</label>\r\n                    <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" name=\"NewPassword\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-2\"");

WriteLiteral(">确认密码</label>\r\n                    <div");

WriteLiteral(" class=\"input-group col-md-6\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" name=\"NewPassword2\"");

WriteLiteral(" type=\"password\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"clearfix form-actions\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4\"");

WriteLiteral("></label>\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-save\"");

WriteLiteral("></i><strong>保存</strong></button>\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-danger btn-sm\"");

WriteLiteral(" onclick=\"history.go(-1);\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-remove\"");

WriteLiteral("></i><strong>取消</strong></button>\r\n                </div>\r\n");

            
            #line 57 "..\..\Areas\Admin\Views\User\ChangePassword.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
