/**
 * 图标工具：后端菜单图标字符串 → antd 图标组件
 *
 * 数据库菜单图标来源多样（历史遗留），需兼容三套命名：
 * - FontAwesome 风格：`fa-table` / `fa-cog`（MVC 皮肤时代）
 * - Element Plus 风格：`Monitor` / `UserFilled` / `Odometer`（Vue/ElementUI 皮肤时代，本库当前主流）
 * - antd 风格：`TableOutlined` / `UserOutlined`（React 皮肤内部）
 *
 * 未命中统一回退默认图标，绝不白屏。
 */
import type { ReactNode } from 'react';
import {
  AimOutlined,
  AppstoreOutlined,
  AudioOutlined,
  BankOutlined,
  BarChartOutlined,
  BellOutlined,
  CalendarOutlined,
  CameraOutlined,
  CheckCircleOutlined,
  CloudOutlined,
  CloudServerOutlined,
  CompassOutlined,
  ControlOutlined,
  CopyOutlined,
  CreditCardOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DesktopOutlined,
  DownloadOutlined,
  EditOutlined,
  EnvironmentOutlined,
  EyeOutlined,
  FieldTimeOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileImageOutlined,
  FilePdfOutlined,
  FileTextOutlined,
  FileZipOutlined,
  FilterOutlined,
  FlagOutlined,
  FolderOutlined,
  FolderOpenOutlined,
  FundOutlined,
  HomeOutlined,
  IdcardOutlined,
  InboxOutlined,
  KeyOutlined,
  LineChartOutlined,
  LinkOutlined,
  LockOutlined,
  MailOutlined,
  MenuFoldOutlined,
  MenuOutlined,
  MenuUnfoldOutlined,
  MessageOutlined,
  MobileOutlined,
  PaperClipOutlined,
  PayCircleOutlined,
  PhoneOutlined,
  PictureOutlined,
  PieChartOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  ProfileOutlined,
  ReadOutlined,
  ReloadOutlined,
  SafetyOutlined,
  SaveOutlined,
  SearchOutlined,
  SettingOutlined,
  ShareAltOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  StarOutlined,
  SwapOutlined,
  TableOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TrophyOutlined,
  UnlockOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  QuestionCircleOutlined,
} from '@ant-design/icons';

const ICON_MAP: Record<string, ReactNode> = {
  // ===== 简单名（React 皮肤早期 IconSelector 值） =====
  table: <TableOutlined />,
  user: <UserOutlined />,
  team: <TeamOutlined />,
  setting: <SettingOutlined />,
  dashboard: <DashboardOutlined />,
  file: <FileTextOutlined />,
  home: <HomeOutlined />,
  appstore: <AppstoreOutlined />,
  safety: <SafetyOutlined />,
  bell: <BellOutlined />,
  database: <DatabaseOutlined />,
  tool: <ToolOutlined />,
  chart: <BarChartOutlined />,
  folder: <FolderOutlined />,
  cloud: <CloudOutlined />,
  key: <KeyOutlined />,
  menu: <MenuOutlined />,
  lock: <LockOutlined />,
  save: <SaveOutlined />,
  search: <SearchOutlined />,

  // ===== FontAwesome 风格（MVC 皮肤时代） =====
  'fa-table': <TableOutlined />,
  'fa-user': <UserOutlined />,
  'fa-users': <TeamOutlined />,
  'fa-cog': <SettingOutlined />,
  'fa-dashboard': <DashboardOutlined />,
  'fa-file': <FileTextOutlined />,
  'fa-home': <HomeOutlined />,
  'fa-th-large': <AppstoreOutlined />,
  'fa-shield': <SafetyOutlined />,
  'fa-bell': <BellOutlined />,
  'fa-database': <DatabaseOutlined />,
  'fa-wrench': <ToolOutlined />,
  'fa-bar-chart': <BarChartOutlined />,
  'fa-folder': <FolderOutlined />,
  'fa-cloud': <CloudOutlined />,
  'fa-key': <KeyOutlined />,
  'fa-list': <MenuOutlined />,
  'fa-lock': <LockOutlined />,
  'fa-save': <SaveOutlined />,
  'fa-search': <SearchOutlined />,
  'fa-download': <DownloadOutlined />,
  'fa-upload': <UploadOutlined />,
  'fa-edit': <EditOutlined />,
  'fa-trash': <DeleteOutlined />,
  'fa-plus': <PlusOutlined />,
  'fa-star': <StarOutlined />,
  'fa-clock': <FieldTimeOutlined />,
  'fa-calendar': <CalendarOutlined />,
  'fa-envelope': <MailOutlined />,
  'fa-phone': <PhoneOutlined />,
  'fa-camera': <CameraOutlined />,
  'fa-picture': <PictureOutlined />,
  'fa-link': <LinkOutlined />,
  'fa-eye': <EyeOutlined />,
  'fa-flag': <FlagOutlined />,
  'fa-trophy': <TrophyOutlined />,
  'fa-money': <PayCircleOutlined />,
  'fa-credit-card': <CreditCardOutlined />,
  'fa-shopping-cart': <ShoppingCartOutlined />,
  'fa-shopping-bag': <ShoppingOutlined />,
  'fa-filter': <FilterOutlined />,
  'fa-refresh': <ReloadOutlined />,
  'fa-share': <ShareAltOutlined />,
  'fa-globe': <CloudOutlined />,
  'fa-server': <CloudServerOutlined />,
  'fa-cube': <AppstoreOutlined />,
  'fa-book': <ReadOutlined />,
  'fa-gear': <SettingOutlined />,

  // ===== Element Plus 风格（Vue/ElementUI 皮肤时代，数据库当前标准） =====
  Monitor: <DesktopOutlined />,
  User: <UserOutlined />,
  UserFilled: <UserOutlined />,
  CirclePlus: <PlusCircleOutlined />,
  Operation: <ControlOutlined />,
  Menu: <MenuOutlined />,
  Avatar: <IdcardOutlined />,
  Timer: <FieldTimeOutlined />,
  Tools: <ToolOutlined />,
  DataBoard: <DashboardOutlined />,
  Odometer: <DashboardOutlined />,
  DataLine: <LineChartOutlined />,
  Star: <StarOutlined />,
  Document: <FileTextOutlined />,
  Clock: <FieldTimeOutlined />,
  Setting: <SettingOutlined />,
  Goods: <ShoppingOutlined />,
  ShoppingCart: <ShoppingCartOutlined />,
  List: <MenuOutlined />,
  Grid: <AppstoreOutlined />,
  HomeFilled: <HomeOutlined />,
  House: <HomeOutlined />,
  DataAnalysis: <FundOutlined />,
  TrendCharts: <LineChartOutlined />,
  PieChart: <PieChartOutlined />,
  Histogram: <BarChartOutlined />,
  Notebook: <FileTextOutlined />,
  Folder: <FolderOutlined />,
  FolderOpened: <FolderOpenOutlined />,
  Box: <InboxOutlined />,
  Package: <InboxOutlined />,
  Lock: <LockOutlined />,
  Unlock: <UnlockOutlined />,
  Key: <KeyOutlined />,
  Link: <LinkOutlined />,
  Share: <ShareAltOutlined />,
  Bell: <BellOutlined />,
  Message: <MessageOutlined />,
  ChatDotRound: <MessageOutlined />,
  Phone: <PhoneOutlined />,
  Iphone: <MobileOutlined />,
  Mobile: <MobileOutlined />,
  Cpu: <CloudServerOutlined />,
  Server: <CloudServerOutlined />,
  Cloudy: <CloudOutlined />,
  Cloud: <CloudOutlined />,
  Download: <DownloadOutlined />,
  Upload: <UploadOutlined />,
  Refresh: <ReloadOutlined />,
  RefreshRight: <ReloadOutlined />,
  Search: <SearchOutlined />,
  Plus: <PlusOutlined />,
  Close: <DeleteOutlined />,
  Check: <CheckCircleOutlined />,
  Delete: <DeleteOutlined />,
  Edit: <EditOutlined />,
  EditPen: <EditOutlined />,
  Reading: <ReadOutlined />,
  Tickets: <ProfileOutlined />,
  Collection: <ProfileOutlined />,
  Guide: <CompassOutlined />,
  MapLocation: <EnvironmentOutlined />,
  Location: <EnvironmentOutlined />,
  Position: <EnvironmentOutlined />,
  Compass: <CompassOutlined />,
  Flag: <FlagOutlined />,
  Medal: <TrophyOutlined />,
  Trophy: <TrophyOutlined />,
  Aim: <AimOutlined />,
  Coin: <PayCircleOutlined />,
  Money: <PayCircleOutlined />,
  Wallet: <WalletOutlined />,
  CreditCard: <CreditCardOutlined />,
  BankCard: <CreditCardOutlined />,
  PriceTag: <TagsOutlined />,
  Calendar: <CalendarOutlined />,
  AlarmClock: <FieldTimeOutlined />,
  Watch: <FieldTimeOutlined />,
  Stopwatch: <FieldTimeOutlined />,
  Paperclip: <PaperClipOutlined />,
  CopyDocument: <CopyOutlined />,
  DocumentCopy: <CopyOutlined />,
  DocumentChecked: <FileDoneOutlined />,
  DocumentAdd: <FileAddOutlined />,
  Picture: <PictureOutlined />,
  PictureFilled: <PictureOutlined />,
  Camera: <CameraOutlined />,
  VideoCamera: <VideoCameraOutlined />,
  Mic: <AudioOutlined />,
  Headset: <CustomerServiceOutlined />,
  Music: <AudioOutlined />,
  Service: <CustomerServiceOutlined />,
  MagicStick: <ThunderboltOutlined />,
  Lightning: <ThunderboltOutlined />,
  Thunderbolt: <ThunderboltOutlined />,
  Switch: <SwapOutlined />,
  SwitchButton: <SwapOutlined />,
  Connection: <CloudServerOutlined />,
  SetUp: <ToolOutlined />,
  Fold: <MenuFoldOutlined />,
  Expand: <MenuUnfoldOutlined />,
  Rank: <SortAscendingOutlined />,
  Sort: <SortAscendingOutlined />,
  SortUp: <SortAscendingOutlined />,
  SortDown: <SortDescendingOutlined />,
  Filter: <FilterOutlined />,
  ZoomIn: <ZoomInOutlined />,
  ZoomOut: <ZoomOutOutlined />,
  View: <EyeOutlined />,
  Hide: <EyeOutlined />,
  AvatarFilled: <IdcardOutlined />,
  Idcard: <IdcardOutlined />,
  Files: <FolderOutlined />,
  DocumentRemove: <FileTextOutlined />,
  DocumentDelete: <FileTextOutlined />,
  DocumentView: <FileTextOutlined />,
  DocumentDownload: <DownloadOutlined />,
  DocumentUpload: <UploadOutlined />,
  Memo: <ProfileOutlined />,
  Notepad: <FileTextOutlined />,
  DataLineFilled: <LineChartOutlined />,
  MonitorFilled: <DesktopOutlined />,
  MenuFilled: <MenuOutlined />,
  ToolsFilled: <ToolOutlined />,
  TimerFilled: <FieldTimeOutlined />,
  SettingFilled: <SettingOutlined />,
  StarFilled: <StarOutlined />,
  ClockFilled: <FieldTimeOutlined />,
};

/** 动态解析 antd 图标名（如 "TableOutlined" / "UserOutlined"），需在下方显式登记 */
const DYNAMIC_ICONS: Record<string, ReactNode> = {
  TableOutlined: <TableOutlined />,
  UserOutlined: <UserOutlined />,
  TeamOutlined: <TeamOutlined />,
  SettingOutlined: <SettingOutlined />,
  DashboardOutlined: <DashboardOutlined />,
  FileTextOutlined: <FileTextOutlined />,
  HomeOutlined: <HomeOutlined />,
  AppstoreOutlined: <AppstoreOutlined />,
  SafetyOutlined: <SafetyOutlined />,
  BellOutlined: <BellOutlined />,
  DatabaseOutlined: <DatabaseOutlined />,
  ToolOutlined: <ToolOutlined />,
  BarChartOutlined: <BarChartOutlined />,
  FolderOutlined: <FolderOutlined />,
  CloudOutlined: <CloudOutlined />,
  KeyOutlined: <KeyOutlined />,
  MenuOutlined: <MenuOutlined />,
  LockOutlined: <LockOutlined />,
  SaveOutlined: <SaveOutlined />,
  SearchOutlined: <SearchOutlined />,
  DesktopOutlined: <DesktopOutlined />,
  PlusCircleOutlined: <PlusCircleOutlined />,
  ControlOutlined: <ControlOutlined />,
  IdcardOutlined: <IdcardOutlined />,
  FieldTimeOutlined: <FieldTimeOutlined />,
  LineChartOutlined: <LineChartOutlined />,
  StarOutlined: <StarOutlined />,
  FundOutlined: <FundOutlined />,
  PieChartOutlined: <PieChartOutlined />,
  DownloadOutlined: <DownloadOutlined />,
  UploadOutlined: <UploadOutlined />,
  ReloadOutlined: <ReloadOutlined />,
  EditOutlined: <EditOutlined />,
  DeleteOutlined: <DeleteOutlined />,
  PlusOutlined: <PlusOutlined />,
  CalendarOutlined: <CalendarOutlined />,
  MailOutlined: <MailOutlined />,
  PhoneOutlined: <PhoneOutlined />,
  CameraOutlined: <CameraOutlined />,
  PictureOutlined: <PictureOutlined />,
  LinkOutlined: <LinkOutlined />,
  EyeOutlined: <EyeOutlined />,
  FlagOutlined: <FlagOutlined />,
  TrophyOutlined: <TrophyOutlined />,
  PayCircleOutlined: <PayCircleOutlined />,
  CreditCardOutlined: <CreditCardOutlined />,
  ShoppingCartOutlined: <ShoppingCartOutlined />,
  ShoppingOutlined: <ShoppingOutlined />,
  FilterOutlined: <FilterOutlined />,
  ShareAltOutlined: <ShareAltOutlined />,
  CloudServerOutlined: <CloudServerOutlined />,
  ReadOutlined: <ReadOutlined />,
  FolderOpenOutlined: <FolderOpenOutlined />,
  InboxOutlined: <InboxOutlined />,
  MessageOutlined: <MessageOutlined />,
  MobileOutlined: <MobileOutlined />,
  CompassOutlined: <CompassOutlined />,
  EnvironmentOutlined: <EnvironmentOutlined />,
  AimOutlined: <AimOutlined />,
  WalletOutlined: <WalletOutlined />,
  TagsOutlined: <TagsOutlined />,
  PaperClipOutlined: <PaperClipOutlined />,
  CopyOutlined: <CopyOutlined />,
  FileDoneOutlined: <FileDoneOutlined />,
  FileAddOutlined: <FileAddOutlined />,
  VideoCameraOutlined: <VideoCameraOutlined />,
  AudioOutlined: <AudioOutlined />,
  CustomerServiceOutlined: <CustomerServiceOutlined />,
  ThunderboltOutlined: <ThunderboltOutlined />,
  SwapOutlined: <SwapOutlined />,
  MenuFoldOutlined: <MenuFoldOutlined />,
  MenuUnfoldOutlined: <MenuUnfoldOutlined />,
  SortAscendingOutlined: <SortAscendingOutlined />,
  SortDescendingOutlined: <SortDescendingOutlined />,
  ZoomInOutlined: <ZoomInOutlined />,
  ZoomOutOutlined: <ZoomOutOutlined />,
  CheckCircleOutlined: <CheckCircleOutlined />,
  ProfileOutlined: <ProfileOutlined />,
  FileExcelOutlined: <FileExcelOutlined />,
  FileImageOutlined: <FileImageOutlined />,
  FilePdfOutlined: <FilePdfOutlined />,
  FileZipOutlined: <FileZipOutlined />,
  BankOutlined: <BankOutlined />,
};

/**
 * 将后端图标字符串转为 antd 图标节点
 *
 * 兼容三套命名（FontAwesome / Element Plus / antd Outlined），未命中返回默认图标。
 *
 * @param icon 图标字符串（如 fa-table / Monitor / UserOutlined）
 * @returns 图标节点，未命中返回默认图标
 */
export function resolveIcon(icon?: string): ReactNode {
  if (!icon) return <MenuOutlined />;
  const key = icon.trim();
  const lower = key.toLowerCase();

  // 1. 精确映射表（Element Plus / FontAwesome / 简单名）
  const mapped = ICON_MAP[key] ?? ICON_MAP[lower];
  if (mapped) return mapped;

  // 2. 动态解析 antd 图标名（如 "UserOutlined"、"FolderOutlined"）
  const dyn = DYNAMIC_ICONS[key];
  if (dyn) return dyn;

  return <QuestionCircleOutlined />;
}

export default resolveIcon;
