#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    
    #line 4 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Area/_List_Data.cshtml")]
    public partial class _Areas_Admin_Views_Area__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<Area>>
    {
        public _Areas_Admin_Views_Area__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 9 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityFactory;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var set = ViewBag.PageSetting as PageSetting;
    var provider = ManageProvider.Provider;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
             if (set.EnableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"编码。行政区划编码\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 766), Tuple.Create("\"", 805)
            
            #line 23 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 773), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 773), false)
);

WriteLiteral(">编码</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 858), Tuple.Create("\"", 899)
            
            #line 24 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 865), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Name"))
            
            #line default
            #line hidden
, 865), false)
);

WriteLiteral(">名称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 952), Tuple.Create("\"", 997)
            
            #line 25 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 959), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("FullName"))
            
            #line default
            #line hidden
, 959), false)
);

WriteLiteral(">全名</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1050), Tuple.Create("\"", 1095)
            
            #line 26 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1057), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ParentID"))
            
            #line default
            #line hidden
, 1057), false)
);

WriteLiteral(">父级</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">下级</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1193), Tuple.Create("\"", 1235)
            
            #line 28 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1200), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Level"))
            
            #line default
            #line hidden
, 1200), false)
);

WriteLiteral(">层级</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1288), Tuple.Create("\"", 1329)
            
            #line 29 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1295), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Kind"))
            
            #line default
            #line hidden
, 1295), false)
);

WriteLiteral(">类型</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"区号。电话区号\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1398), Tuple.Create("\"", 1442)
            
            #line 30 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1405), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("TelCode"))
            
            #line default
            #line hidden
, 1405), false)
);

WriteLiteral(">区号</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"邮编。邮政编码\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1511), Tuple.Create("\"", 1555)
            
            #line 31 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1518), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ZipCode"))
            
            #line default
            #line hidden
, 1518), false)
);

WriteLiteral(">邮编</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1608), Tuple.Create("\"", 1654)
            
            #line 32 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1615), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Longitude"))
            
            #line default
            #line hidden
, 1615), false)
);

WriteLiteral(">经度</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1707), Tuple.Create("\"", 1752)
            
            #line 33 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1714), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Latitude"))
            
            #line default
            #line hidden
, 1714), false)
);

WriteLiteral(">纬度</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"字符串前缀相同越多，地理距离越近，8位精度19米，6位610米\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1845), Tuple.Create("\"", 1889)
            
            #line 34 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
     , Tuple.Create(Tuple.Create("", 1852), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("GeoHash"))
            
            #line default
            #line hidden
, 1852), false)
);

WriteLiteral(">地址编码</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1944), Tuple.Create("\"", 1987)
            
            #line 35 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1951), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Enable"))
            
            #line default
            #line hidden
, 1951), false)
);

WriteLiteral(">启用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2065), Tuple.Create("\"", 2112)
            
            #line 36 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2072), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("CreateTime"))
            
            #line default
            #line hidden
, 2072), false)
);

WriteLiteral(">更新时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2192), Tuple.Create("\"", 2239)
            
            #line 37 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2199), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateTime"))
            
            #line default
            #line hidden
, 2199), false)
);

WriteLiteral(">更新时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2294), Tuple.Create("\"", 2337)
            
            #line 38 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2301), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Remark"))
            
            #line default
            #line hidden
, 2301), false)
);

WriteLiteral(">备注</a></th>\r\n");

            
            #line 39 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 39 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 42 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 46 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 46 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
         foreach (var entity in Model)
        {
            var pstr = entity.Parent != null ? (entity.Parent + "") : (entity.ParentID + "");

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 50 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 50 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                 if (set.EnableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2874), Tuple.Create("\"", 2892)
            
            #line 52 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 2882), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2882), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 53 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 54 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 55 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
               Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 56 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
               Write(entity.FullName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3103), Tuple.Create("\"", 3130)
, Tuple.Create(Tuple.Create("", 3110), Tuple.Create("?Id=", 3110), true)
            
            #line 57 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3114), Tuple.Create<System.Object, System.Int32>(entity.ParentID
            
            #line default
            #line hidden
, 3114), false)
);

WriteLiteral(">");

            
            #line 57 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                                                  Write(pstr);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3190), Tuple.Create("\"", 3217)
, Tuple.Create(Tuple.Create("", 3197), Tuple.Create("?parentId=", 3197), true)
            
            #line 58 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3207), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 3207), false)
);

WriteLiteral(">下级</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 59 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.Level);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 60 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.Kind);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 61 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.TelCode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 62 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.ZipCode);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 63 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                  Write(entity.Longitude);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 64 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                  Write(entity.Latitude);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 65 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.GeoHash);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3726), Tuple.Create("\"", 3788)
, Tuple.Create(Tuple.Create("", 3734), Tuple.Create("glyphicon", 3734), true)
, Tuple.Create(Tuple.Create(" ", 3743), Tuple.Create("glyphicon-", 3744), true)
            
            #line 67 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3754), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "ok" : "remove"
            
            #line default
            #line hidden
, 3754), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 3789), Tuple.Create("\"", 3839)
, Tuple.Create(Tuple.Create("", 3797), Tuple.Create("color:", 3797), true)
            
            #line 67 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                    , Tuple.Create(Tuple.Create(" ", 3803), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "green" : "red"
            
            #line default
            #line hidden
, 3804), false)
, Tuple.Create(Tuple.Create("", 3838), Tuple.Create(";", 3838), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 69 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.CreateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 70 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.UpdateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 71 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.UpdateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 72 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
               Write(entity.Remark);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 73 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 73 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 76 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 78 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 80 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
