#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    
    #line 4 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using XCode;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using XCode.Configuration;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
    using XCode.Membership;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Area/_List_Data.cshtml")]
    public partial class _Areas_Admin_Views_Area__List_Data_cshtml : System.Web.Mvc.WebViewPage<IList<Area>>
    {
        public _Areas_Admin_Views_Area__List_Data_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 9 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
  
    var fact = ViewBag.Factory as IEntityFactory;
    var page = ViewBag.Page as Pager;
    var fields = ViewBag.Fields as IList<FieldItem>;
    var set = ViewBag.PageSetting as PageSetting;
    var provider = ManageProvider.Provider;

            
            #line default
            #line hidden
WriteLiteral("\r\n<table");

WriteLiteral(" class=\"table table-bordered table-hover table-striped table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
             if (set.EnableSelect)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"width:10px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"chkAll\"");

WriteLiteral(" title=\"全选\"");

WriteLiteral(" /></th>\r\n");

            
            #line 22 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" title=\"编码。行政区划编码\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 766), Tuple.Create("\"", 805)
            
            #line 23 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 773), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ID"))
            
            #line default
            #line hidden
, 773), false)
);

WriteLiteral(">编码</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 858), Tuple.Create("\"", 899)
            
            #line 24 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 865), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Name"))
            
            #line default
            #line hidden
, 865), false)
);

WriteLiteral(">名称</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 952), Tuple.Create("\"", 997)
            
            #line 25 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 959), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("FullName"))
            
            #line default
            #line hidden
, 959), false)
);

WriteLiteral(">全名</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1050), Tuple.Create("\"", 1095)
            
            #line 26 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1057), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("ParentID"))
            
            #line default
            #line hidden
, 1057), false)
);

WriteLiteral(">父级</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">下级</th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1193), Tuple.Create("\"", 1235)
            
            #line 28 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1200), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Level"))
            
            #line default
            #line hidden
, 1200), false)
);

WriteLiteral(">层级</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1288), Tuple.Create("\"", 1334)
            
            #line 29 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1295), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Longitude"))
            
            #line default
            #line hidden
, 1295), false)
);

WriteLiteral(">经度</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1387), Tuple.Create("\"", 1432)
            
            #line 30 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1394), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Latitude"))
            
            #line default
            #line hidden
, 1394), false)
);

WriteLiteral(">纬度</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1485), Tuple.Create("\"", 1528)
            
            #line 31 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1492), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Enable"))
            
            #line default
            #line hidden
, 1492), false)
);

WriteLiteral(">启用</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1581), Tuple.Create("\"", 1628)
            
            #line 32 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1588), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateUser"))
            
            #line default
            #line hidden
, 1588), false)
);

WriteLiteral(">更新者</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1682), Tuple.Create("\"", 1731)
            
            #line 33 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1689), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateUserID"))
            
            #line default
            #line hidden
, 1689), false)
);

WriteLiteral(">更新用户</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1786), Tuple.Create("\"", 1831)
            
            #line 34 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1793), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateIP"))
            
            #line default
            #line hidden
, 1793), false)
);

WriteLiteral(">更新地址</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:134px;\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 1911), Tuple.Create("\"", 1958)
            
            #line 35 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 1918), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("UpdateTime"))
            
            #line default
            #line hidden
, 1918), false)
);

WriteLiteral(">更新时间</a></th>\r\n            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2013), Tuple.Create("\"", 2056)
            
            #line 36 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2020), Tuple.Create<System.Object, System.Int32>(Html.Raw(page.GetSortUrl("Remark"))
            
            #line default
            #line hidden
, 2020), false)
);

WriteLiteral(">备注</a></th>\r\n");

            
            #line 37 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
            
            
            #line default
            #line hidden
            
            #line 37 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
             if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">操作</th>\r\n");

            
            #line 40 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 44 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
        
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
         foreach (var entity in Model)
        {
            var pstr = entity.Parent != null ? (entity.Parent + "") : (entity.ParentID + "");

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 48 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 48 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                 if (set.EnableSelect)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"keys\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2593), Tuple.Create("\"", 2611)
            
            #line 50 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
      , Tuple.Create(Tuple.Create("", 2601), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2601), false)
);

WriteLiteral(" /></td>\r\n");

            
            #line 51 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 52 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.ID);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 53 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
               Write(entity.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 54 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
               Write(entity.FullName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2822), Tuple.Create("\"", 2849)
, Tuple.Create(Tuple.Create("", 2829), Tuple.Create("?Id=", 2829), true)
            
            #line 55 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2833), Tuple.Create<System.Object, System.Int32>(entity.ParentID
            
            #line default
            #line hidden
, 2833), false)
);

WriteLiteral(">");

            
            #line 55 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                                                  Write(pstr);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 2909), Tuple.Create("\"", 2936)
, Tuple.Create(Tuple.Create("", 2916), Tuple.Create("?parentId=", 2916), true)
            
            #line 56 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 2926), Tuple.Create<System.Object, System.Int32>(entity.ID
            
            #line default
            #line hidden
, 2926), false)
);

WriteLiteral(">下级</a></td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 57 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.Level);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 58 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                  Write(entity.Longitude.ToString("n2"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">");

            
            #line 59 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                  Write(entity.Latitude.ToString("n2"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 3230), Tuple.Create("\"", 3292)
, Tuple.Create(Tuple.Create("", 3238), Tuple.Create("glyphicon", 3238), true)
, Tuple.Create(Tuple.Create(" ", 3247), Tuple.Create("glyphicon-", 3248), true)
            
            #line 61 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3258), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "ok" : "remove"
            
            #line default
            #line hidden
, 3258), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 3293), Tuple.Create("\"", 3343)
, Tuple.Create(Tuple.Create("", 3301), Tuple.Create("color:", 3301), true)
            
            #line 61 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                    , Tuple.Create(Tuple.Create(" ", 3307), Tuple.Create<System.Object, System.Int32>(entity.Enable ? "green" : "red"
            
            #line default
            #line hidden
, 3308), false)
, Tuple.Create(Tuple.Create("", 3342), Tuple.Create(";", 3342), true)
);

WriteLiteral("></i>\r\n                </td>\r\n                <td>");

            
            #line 63 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
               Write(entity.UpdateUser);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 64 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(provider.FindByID(entity.UpdateUserID));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteAttribute("title", Tuple.Create(" title=\"", 3544), Tuple.Create("\"", 3582)
            
            #line 65 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
, Tuple.Create(Tuple.Create("", 3552), Tuple.Create<System.Object, System.Int32>(entity.UpdateIP.IPToAddress()
            
            #line default
            #line hidden
, 3552), false)
);

WriteLiteral(">");

            
            #line 65 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                                                          Write(entity.UpdateIP);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">");

            
            #line 66 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                                   Write(entity.UpdateTime.ToFullString(""));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 67 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
               Write(entity.Remark);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 68 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                
            
            #line default
            #line hidden
            
            #line 68 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                 if (this.Has(PermissionFlags.Detail, PermissionFlags.Update, PermissionFlags.Delete))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 71 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                   Write(Html.Partial("_List_Data_Action", (Object)entity));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n");

            
            #line 73 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tr>\r\n");

            
            #line 75 "..\..\Areas\Admin\Views\Area\_List_Data.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
