/**
 * IconPark 图标组件注册表（OSC-0017）
 *
 * 按需具名引入 `@icon-park/vue-next` 各图标组件（tree-shakeable，仅打包用到的图标），
 * 建立 kebab-case 图标名 → 组件映射，供全局 `<icon-park :type>` 动态组件渲染。
 *
 * 全量 `install(app, 'icon')` 会把 2658 个图标全部打入 bundle（约 387KB gzip），
 * 明显膨胀，故降级为按需引入（design §10）。本表为唯一引入点，新增图标须在此登记。
 */
import type { Component } from 'vue';
import {
  AddUser,
  Application,
  ApplicationMenu,
  Attention,
  BigClock,
  BackgroundColor,
  Blackboard,
  Box,
  BuildingOne,
  Calendar,
  ChartHistogram,
  ChartHistogramOne,
  ChartHistogramTwo,
  ChartLine,
  ChartPie,
  Check,
  Checklist,
  Click,
  Close,
  Comments,
  Computer,
  ConnectionBox,
  Copy,
  CubeThree,
  Dashboard,
  Data,
  DeathStar,
  Delete,
  Down,
  Download,
  Drag,
  Edit,
  EditTwo,
  Export,
  FacialMask,
  FileAddition,
  FileText,
  Filter,
  FullScreen,
  FontSize,
  GridFour,
  Group,
  History,
  Home,
  Inbox,
  Info,
  Key,
  LayoutOne,
  Left,
  LeftBar,
  Link,
  LinkBreak,
  Lightning,
  List,
  ListCheckbox,
  ListNumbers,
  Lock,
  Login,
  Logout,
  Mail,
  MenuFold,
  MenuUnfold,
  Message,
  Moon,
  More,
  MoreOne,
  NetworkTree,
  People,
  Peoples,
  Permissions,
  Phone,
  Pic,
  Plus,
  PreviewClose,
  PreviewOpen,
  OffScreen,
  Refresh,
  Remind,
  Right,
  RightBar,
  RobotOne,
  Save,
  Search,
  Send,
  Setting,
  SettingConfig,
  Share,
  ShoppingBag,
  Star,
  Sun,
  Switch,
  Tag,
  Time,
  Timeline,
  Timer,
  Tool,
  TreeList,
  Undo,
  Up,
  Upload,
  User,
  Workbench,
} from '@icon-park/vue-next';

/** kebab-case 图标名 → 组件（与 iconRegistry.ts 注册的图标名一一对应） */
export const ICON_COMPONENTS: Record<string, Component> = {
  // 视图类型
  'list-checkbox': ListCheckbox,
  'tree-list': TreeList,
  pic: Pic,
  blackboard: Blackboard,
  calendar: Calendar,
  timeline: Timeline,
  // 外观
  sun: Sun,
  moon: Moon,
  computer: Computer,
  // 字段类型
  'file-text': FileText,
  link: Link,
  unlink: LinkBreak,
  mail: Mail,
  logout: Logout,
  phone: Phone,
  switch: Switch,
  time: Time,
  tag: Tag,
  'list-numbers': ListNumbers,
  key: Key,
  'font-size': FontSize,
  // 菜单（fa 映射 + 关键词兜底）
  people: People,
  peoples: Peoples,
  'add-user': AddUser,
  user: User,
  'facial-mask': FacialMask,
  list: List,
  lock: Lock,
  lightning: Lightning,
  tool: Tool,
  setting: Setting,
  'setting-config': SettingConfig,
  data: Data,
  history: History,
  'big-clock': BigClock,
  checklist: Checklist,
  star: Star,
  home: Home,
  search: Search,
  dashboard: Dashboard,
  workbench: Workbench,
  'chart-line': ChartLine,
  'chart-histogram': ChartHistogram,
  'chart-histogram-one': ChartHistogramOne,
  'chart-histogram-two': ChartHistogramTwo,
  'chart-pie': ChartPie,
  'shopping-bag': ShoppingBag,
  'death-star': DeathStar,
  'grid-four': GridFour,
  permissions: Permissions,
  timer: Timer,
  send: Send,
  share: Share,
  message: Message,
  'building-one': BuildingOne,
  box: Box,
  inbox: Inbox,
  application: Application,
  'application-menu': ApplicationMenu,
  login: Login,
  attention: Attention,
  // 产品命名专用
  'cube-three': CubeThree,
  'connection-box': ConnectionBox,
  // 工具栏 / 表单 / 视图配置
  filter: Filter,
  'background-color': BackgroundColor,
  'full-screen': FullScreen,
  group: Group,
  more: More,
  'more-one': MoreOne,
  download: Download,
  'off-screen': OffScreen,
  export: Export,
  delete: Delete,
  'layout-one': LayoutOne,
  down: Down,
  up: Up,
  upload: Upload,
  refresh: Refresh,
  remind: Remind,
  check: Check,
  save: Save,
  edit: Edit,
  copy: Copy,
  undo: Undo,
  'menu-fold': MenuFold,
  'menu-unfold': MenuUnfold,
  close: Close,
  info: Info,
  drag: Drag,
  'preview-open': PreviewOpen,
  'preview-close': PreviewClose,
  'left-bar': LeftBar,
  'right-bar': RightBar,
  // 自动化中心 / 流程编辑（OSC-260815fa86）
  plus: Plus,
  left: Left,
  right: Right,
  'robot-one': RobotOne,
  'file-addition': FileAddition,
  'edit-two': EditTwo,
  click: Click,
  comments: Comments,
  'network-tree': NetworkTree,
};

/** 兜底图标（无效/未登记 type 时渲染，避免运行时抛错） */
export const FALLBACK_ICON = Application;
